### PR TITLE
Fix: Include source code snippets in `hint-compat-api`

### LINKED ISSUE #2210: [Bug] `hint-compat-api` doesn't include source code snippets [1.7]
A number of other hints include snippets of source code along with reports to make it easier to find what needs to be changed. However, `hint-compat-api` does not include these in its reports, making it more difficult to get context.

### PR DESCRIPTION
**Pull request by sarvaje**
Fix #2210

## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [x] Added/Updated related documentation.
- [x] Added/Updated related tests.

### CODE REVIEW

File: packages/hint-compat-api/src/helpers/compat-css.ts [hunk 1]
```diff
@@ -26,7 +26,7 @@ export class CompatCSS extends CompatBase<StyleEvents, StyleParse> {
     }
 
     public searchFeatures(parse: StyleParse): void {
-        this.walk(parse.ast);
+        this.walk(parse.ast, parse.code);
```
Comment (antross) [inline packages/hint-compat-api/src/helpers/compat-css.ts]: I think we want something narrower than the entire CSS file. We should either omit this for CSS or only include code which is near the problem. 

If we want to serialize something custom I think having the selector plus the relevant CSS property/value (ignoring all other surrounding properties) would be good.

@webhintio/contributors Thoughts?

Comment (molant) [reply packages/hint-compat-api/src/helpers/compat-css.ts]: Definitely, somehow I thought `walk` did this automatically and it was just a feature we weren't using 😖

Comment (sarvaje) [reply packages/hint-compat-api/src/helpers/compat-css.ts]: I thought `pase.code` had only the feature hehehe. I will look into it.

Comment (sarvaje) [reply packages/hint-compat-api/src/helpers/compat-css.ts]: done!

**Comment by antross** [comment]
One more thing. This gave me the idea that we could link to the Elements panel for this too in the browser extension by passing along the selector and showing the first element which matches (which would get the target CSS active in the "Styles" sub-panel). 

Probably not worth doing in this PR, but could be a good follow-up task if we agree we like it.

File: packages/hint-compat-api/src/helpers/compat-html.ts [hunk 2]
```diff
@@ -23,18 +23,20 @@ export class CompatHTML extends CompatBase<Events, Event> {
         this.walk((elementFound: ElementFound) => {
             const { element, resource } = elementFound;
             const location = element.getLocation();
+            const codeSnippet = element.outerHTML;
```
Comment (antross) [inline packages/hint-compat-api/src/helpers/compat-html.ts]: Also, this can end up including a serialization of most of the page if an element like `<main>` is targeted. Let's add a `utils` helper to do the start-tag-only behavior we've been discussing in #2211. No need to update other hints in this PR, but I'd like to avoid adding new large serializations.

Comment (sarvaje) [reply packages/hint-compat-api/src/helpers/compat-html.ts]: @antross done!

**Comment by sarvaje** [comment]
I still need to update the documentation and add some tests.

**Comment by sarvaje** [comment]
@molant @antross this should be ready to review.

File: packages/utils/src/report/get-css-code-snippet.ts [hunk 3]
```diff
@@ -0,0 +1,111 @@
...
+    let numberOfSpaces = 4;
+    const grandpa = node.parent ? node.parent.parent : null;
+
+    if (grandpa && grandpa.type === 'atrule') {
+        numberOfSpaces = 8;
+    }
+
+    const spaces = new Array(numberOfSpaces + 1).join(' ');
+
+    return `${spaces}${content}`;
```
Comment (antross) [inline packages/utils/src/report/get-css-code-snippet.ts]: This should be a little clearer (also requires deleting `const spaces = ...` above).

```suggestion
    return content.padStart(numberOfSpaces, ' ');
```

File: packages/utils/src/report/get-css-code-snippet.ts [hunk 4]
```diff
@@ -0,0 +1,111 @@
...
+    let numberOfSpaces = 0;
+    const grandpa = node.parent ? node.parent.parent : null;
+
+    if (grandpa) {
+        numberOfSpaces = 4;
+    }
+
+    const spaces = new Array(numberOfSpaces + 1).join(' ');
+
+    return `${spaces}}`;
```
Comment (antross) [inline packages/utils/src/report/get-css-code-snippet.ts]: Again, requires deleting `const spaces = ...` above.

```suggestion
    return '}'.padStart(numberOfSpaces, ' ');
```

File: packages/utils/src/report/get-css-code-snippet.ts (hunk 3 above)
Comment (sarvaje) [reply packages/utils/src/report/get-css-code-snippet.ts]: I didn't like the `new Array` solution, but I couldn't think in a shorter way to do it. Your solution is much better :)

Comment (antross) [reply packages/utils/src/report/get-css-code-snippet.ts]: If only I had written it correctly the first time 🤦‍♂️ Thanks for debugging this with me!

```ts
return content.padStart(content.length + numberOfSpaces, ' ');
```
