### PR TITLE
Fix: Support for URI reserved characters in paths

### LINKED ISSUE #4201: [Bug] Paths with square brackets [file-path] are not resolved
# 🐛 Bug report

## Description

While trying to use WebHint with a Nextjs project, running it on local files that use the Nextjs [dynamic routes](https://nextjs.org/docs/routing/dynamic-routes), the file paths that use square brackets are not resolved and produces an `AnalyzerError: ENOENT: no such file or directory`.

## Environment

* __`hint` version:__ v6.1.1
* __`Node.js` version:__ v14.15.0
* __`OS`:__ Ubuntu-20.04 on WSL2 (Windows)
* __URL for which webhint failed:__ [local connector](https://webhint.io/docs/user-guide/connectors/connector-local/)

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

```js
{
  "connector": {
    "name": "local",
    "options": {
       "pattern": ["**", "!.git/**", "!node_modules/**"]
    }
  },
  "extends": ["development"],
  "formatters": ["stylish"],
  "hints": [
    "button-type",
    "disown-opener",
    "html-checker",
    "meta-charset-utf-8",
    "meta-viewport"
  ]
}
```

</details>

## Debug output

<details>
<summary>webhint’s raw output</summary>

```text
npx hint --debug .
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:app-insights Enabling Application Insights +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb +0ms
  hint:cli:analyze Using language option configured in the OS: C +0ms
  hint:config:config-validator Validating configuration +0ms
  hint:config Composing configuration from extends +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Searching development… +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package @hint/configuration- not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration- not found +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource @hint/configuration-development is not a JSON file, trying to load it normally +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource development found in @hint/configuration-development +1ms
  hint:config:config-validator Validating configuration +33ms
  hint:config Composing configuration from extends +4ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Searching accessibility… +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-development not found +7ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource @hint/configuration-accessibility is not a JSON file, trying to load it normally +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource accessibility found in @hint/configuration-accessibility +0ms
  hint:config:config-validator Validating configuration +8ms
  hint:config Composing configuration from extends +8ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Searching progressive-web-apps… +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-development not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource @hint/configuration-progressive-web-apps is not a JSON file, trying to load it normally +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource progressive-web-apps found in @hint/configuration-progressive-web-apps +1ms
  hint:config:config-validator Validating configuration +3ms
  hint:config Composing configuration from extends +2ms
  hint:config overriding config settings with values provided via CLI +1ms
  hint:config Initializing ignored urls +5ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Searching local… +6ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-accessibility not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-progressive-web-apps not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-development not found +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource @hint/connector-local is not a JSON file, trying to load it normally +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource local found in @hint/connector-local +318ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Searching button-type… +2ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-accessibility not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-progressive-web-apps not found +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-development not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource @hint/hint-button-type is not a JSON file, trying to load it normally +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource button-type found in @hint/hint-button-type +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Searching disown-opener… +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-accessibility not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-progressive-web-apps not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-development not found +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource @hint/hint-disown-opener is not a JSON file, trying to load it normally +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource disown-opener found in @hint/hint-disown-opener +45ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Searching html-checker… +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-accessibility not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-progressive-web-apps not found +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-development not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource @hint/hint-html-checker is not a JSON file, trying to load it normally +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource html-checker found in @hint/hint-html-checker +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Searching meta-charset-utf-8… +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-accessibility not found +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-progressive-web-apps not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-development not found +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource @hint/hint-meta-charset-utf-8 is not a JSON file, trying to load it normally +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource meta-charset-utf-8 found in @hint/hint-meta-charset-utf-8 +2ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Searching meta-viewport… +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-accessibility not found +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-progressive-web-apps not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-development not found +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource @hint/hint-meta-viewport is not a JSON file, trying to load it normally +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource meta-viewport found in @hint/hint-meta-viewport +2ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Searching manifest… +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-accessibility not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-progressive-web-apps not found +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-development not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource @hint/parser-manifest is not a JSON file, trying to load it normally +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource manifest found in @hint/parser-manifest +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Searching babel-config… +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-accessibility not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-progressive-web-apps not found +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-development not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource @hint/parser-babel-config is not a JSON file, trying to load it normally +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource babel-config found in @hint/parser-babel-config +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Searching css… +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-accessibility not found +2ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-progressive-web-apps not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-development not found +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource @hint/parser-css is not a JSON file, trying to load it normally +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource css found in @hint/parser-css +14ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Searching html… +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-accessibility not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-progressive-web-apps not found +5ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-development not found +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource @hint/parser-html is not a JSON file, trying to load it normally +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource html found in @hint/parser-html +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Searching javascript… +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-accessibility not found +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-progressive-web-apps not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-development not found +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource @hint/parser-javascript is not a JSON file, trying to load it normally +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource javascript found in @hint/parser-javascript +9ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Searching jsx… +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-accessibility not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-progressive-web-apps not found +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-development not found +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource @hint/parser-jsx is not a JSON file, trying to load it normally +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource jsx found in @hint/parser-jsx +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Searching less… +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-accessibility not found +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-progressive-web-apps not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-development not found +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource @hint/parser-less is not a JSON file, trying to load it normally +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource less found in @hint/parser-less +21ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Searching sass… +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-accessibility not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-progressive-web-apps not found +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-development not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource @hint/parser-sass is not a JSON file, trying to load it normally +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource sass found in @hint/parser-sass +30ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Searching typescript… +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-accessibility not found +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-progressive-web-apps not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-development not found +2ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource @hint/parser-typescript is not a JSON file, trying to load it normally +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource typescript found in @hint/parser-typescript +208ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Searching typescript-config… +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-accessibility not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-progressive-web-apps not found +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-development not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource @hint/parser-typescript-config is not a JSON file, trying to load it normally +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource typescript-config found in @hint/parser-typescript-config +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Searching webpack-config… +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-accessibility not found +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-progressive-web-apps not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-development not found +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource @hint/parser-webpack-config is not a JSON file, trying to load it normally +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource webpack-config found in @hint/parser-webpack-config +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Searching stylish… +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-accessibility not found +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-progressive-web-apps not found +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Package webhint-configuration-development not found +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource @hint/formatter-stylish is not a JSON file, trying to load it normally +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource stylish found in @hint/formatter-stylish +7ms
  hint:config Validating local connector +705ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Searching local… +1ms
  hint:config Connector schema: +1ms
  hint:config {
  hint:config   additionalProperties: false,
  hint:config   properties: {
  hint:config     pattern: { items: [Object], type: 'array' },
  hint:config     watch: { type: 'boolean' }
  hint:config   }
  hint:config } +0ms
  hint:config User configuration: +2ms
  hint:config undefined +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Searching button-type… +4ms
  hint:config:config-hints Validating hint button-type +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Searching disown-opener… +0ms
  hint:config:config-hints Validating hint disown-opener +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Searching html-checker… +0ms
  hint:config:config-hints Validating hint html-checker +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Searching meta-charset-utf-8… +0ms
  hint:config:config-hints Validating hint meta-charset-utf-8 +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils:dist:src:packages:load-resource Searching meta-viewport… +0ms
  hint:config:config-hints Validating hint meta-viewport +0ms
  hint:engine Initializing hint engine +0ms
  hint:engine Loading parser +1ms
  hint:engine Loading parser +0ms
  hint:engine Loading parser +4ms
  hint:engine Loading parser +1ms
  hint:engine Loading parser +0ms
  hint:engine Loading parser +0ms
  hint:engine Loading parser +0ms
  hint:engine Loading parser +0ms
  hint:engine Loading parser +0ms
  hint:engine Loading parser +0ms
  hint:engine Loading parser +7ms
  hint:engine Parsers loaded: 11 +0ms
  hint:engine Loading hints +0ms
  hint:engine Loading hints +1ms
  hint:engine Loading hints +0ms
  hint:engine Loading hints +0ms
  hint:engine Loading hints +0ms
  hint:engine Starting the analysis on file:///home/rfmaj/Projects/pyphoy/pypweb +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/.eslintrc.json +2s
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/.gitignore +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/.hintrc +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/.nvmrc +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/LICENSE +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/README.md +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/commitlint.config.js +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/next-env.d.ts +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/package-lock.json +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/package.json +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/tsconfig.json +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/types.ts +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/contexts/date-context.ts +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/lib/gtag.ts +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/lib/the-moneytizer.ts +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/pages/_app.tsx +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/pages/_document.tsx +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/pages/index.module.scss +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/pages/index.tsx +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/styles/globals.scss +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/styles/reset.css +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/styles/utils.module.scss +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/styles/vehicles.module.scss +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/public/ads.txt +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/public/android-chrome-192x192.png +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/public/android-chrome-512x512.png +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/public/apple-touch-icon.png +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/public/browserconfig.xml +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/public/favicon-16x16.png +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/public/favicon-32x32.png +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/public/favicon.ico +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/public/mstile-150x150.png +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/public/og-image.png +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/public/safari-pinned-tab.svg +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/public/site.webmanifest +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/utils/utils.ts +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/.github/workflows/build-cron.yml +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/.github/workflows/tests.yml +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/components/call-to-action/call-to-action.module.scss +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/components/call-to-action/call-to-action.tsx +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/components/categories-list/categories-list.module.scss +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/components/categories-list/categories-list.tsx +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/components/category-card/category-card.module.scss +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/components/category-card/category-card.tsx +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/components/category-info/category-info.tsx +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/components/date/date.module.scss +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/components/date/date.tsx +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/components/date/utils.ts +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/components/day-card/day-card.module.scss +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/components/day-card/day-card.tsx +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/components/days-list/days-list.module.scss +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/components/days-list/days-list.tsx +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/components/email/email.tsx +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/components/hour/hour.module.scss +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/components/hour/hour.tsx +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/components/hour/utils.ts +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/components/hours/hours.tsx +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/components/layout/layout.module.scss +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/components/layout/layout.tsx +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/components/license-plate/license-plate.module.scss +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/components/license-plate/license-plate.tsx +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/components/number-links/number-links.module.scss +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/components/number-links/number-links.tsx +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/components/select/select.module.scss +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/components/select/select.tsx +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/pages/%5Bcity%5D/index.tsx +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/pages/api/hello.ts +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/public/fonts/LicensePlate.eot +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/public/fonts/LicensePlate.otf +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/public/fonts/LicensePlate.svg +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/public/fonts/LicensePlate.ttf +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/public/fonts/LicensePlate.woff +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/public/fonts/LicensePlate.woff2 +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/pages/%5Bcity%5D/%5Bcategory%5D/index.tsx +0ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/pages/%5Bcity%5D/%5Bcategory%5D/placa/%5Bnumber%5D/index.module.scss +1ms
  hint:home:rfmaj:Projects:pyphoy:pypweb:node_modules:@hint:utils-network:dist:src:as-uri Adding valid target: file:///home/rfmaj/Projects/pyphoy/pypweb/pages/%5Bcity%5D/%5Bcategory%5D/placa/%5Bnumber%5D/index.tsx +0ms
  hint:cli:analyze Failed to analyze: file:///home/rfmaj/Projects/pyphoy/pypweb +2s
  hint:cli:analyze AnalyzerError: ENOENT: no such file or directory, open '/home/rfmaj/Projects/pyphoy/pypweb/pages/%5Bcity%5D/index.tsx'
  hint:cli:analyze     at Analyzer.analyze (/home/rfmaj/Projects/pyphoy/pypweb/node_modules/hint/dist/src/lib/analyzer.js:151:23)
  hint:cli:analyze     at async exports.default (/home/rfmaj/Projects/pyphoy/pypweb/node_modules/hint/dist/src/lib/cli/analyze.js:317:9)
  hint:cli:analyze     at async /home/rfmaj/Projects/pyphoy/pypweb/node_modules/hint/dist/src/lib/cli/actions.js:8:20
  hint:cli:analyze     at async Object.exports.execute (/home/rfmaj/Projects/pyphoy/pypweb/node_modules/hint/dist/src/lib/cli.js:38:23)
  hint:cli:analyze     at async run (/home/rfmaj/Projects/pyphoy/pypweb/node_modules/hint/dist/src/bin/hint.js:44:24) +1ms
AnalyzerError: ENOENT: no such file or directory, open '/home/rfmaj/Projects/pyphoy/pypweb/pages/%5Bcity%5D/index.tsx'
    at Analyzer.analyze (/home/rfmaj/Projects/pyphoy/pypweb/node_modules/hint/dist/src/lib/analyzer.js:151:23)
    at async exports.default (/home/rfmaj/Projects/pyphoy/pypweb/node_modules/hint/dist/src/lib/cli/analyze.js:317:9)
    at async /home/rfmaj/Projects/pyphoy/pypweb/node_modules/hint/dist/src/lib/cli/actions.js:8:20
    at async Object.exports.execute (/home/rfmaj/Projects/pyphoy/pypweb/node_modules/hint/dist/src/lib/cli.js:38:23)
    at async run (/home/rfmaj/Projects/pyphoy/pypweb/node_modules/hint/dist/src/bin/hint.js:44:24) {
  status: 'AnalyzeError'
}
  hint:cli:analyze Total runtime: 992ms +1ms
```

</details>

### PR DESCRIPTION
**Pull request by johnemau**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [x] Added/Updated related tests.

### Problem
Local connector normalizes paths by converting all paths to URIs
with file protocol which encodes URI reserved characters
(e.g. " space " and [brackets]). This is done with `encodeURI` in
[`file-url`][1] called on packages/utils-network/src/as-uri.ts:49.

The encoded URI pathnames are then passed to the OS and not found:
file:///mnt/[id]/script.js -> (`encodeURI`)
             -> file:///mnt/%5Bid%5D/script.js -> /mnt/%5Bid%5D/script.js

 ### Solution
Decode file protocol pathnames:
/mnt/%5Bid%5D/script.js -> (`decodeURI`) -> /mnt/[id]/script.js

This is the same problem as #3401 which solved the problem of %20 with
string replace in #3409, because `decodeURI` handles all URI encodings
I reverted those lines.

This fix has been tested against:
- https://github.com/vercel/next.js/tree/e28fd50441cfaa22554db2b8e5bb7d03061e67d4/examples/dynamic-routing
- https://github.com/jamesgecko/webhint-space-error/tree/5cb0727264cf8e589bea32e1cf0eefc5a79a8cfe/src

[1]: https://github.com/sindresorhus/file-url/blob/68a06434424e65edf754ea759c24b6a5c05042b5/index.js#L29

Partial revert of #3409
Fix #4201, #3401

### CODE REVIEW

File: packages/utils-network/tests/as-path-string.ts [hunk 1]
```diff
@@ -13,6 +13,22 @@ test('asPathString returns the path name of an "http://" URL', (t) => {
...
+    const url = new URL('https://myresource.com/my/path/%5B-dont-%20-decode-%5D');
+    const expected = '/my/path/%5B-dont-%20-decode-%5D';
+    const actual = asPathString(url);
+
+    t.is(actual, expected, `asPathString doesn't return the encoded path name of an https:// URL`);
+});
+
+test('asPathString returns the decoded path name of an "file:///" URL', (t) => {
+    const url = new URL('file:///my/path/%5Bdecode%20me%5D');
+    const expected = '/my/path/[decode me]';
```
Comment (antross) [inline packages/utils-network/tests/as-path-string.ts:26]: The expected value will vary by OS (which is why this test is currently failing on Windows). Probably should do something similar to the following test in this file.

**Review by antross — COMMENTED** [review]
Nice investigation! Just one test update needed for Windows (and a minor typo fix) then this should be good to go.

**Comment by johnemau** [comment]
> Nice investigation! Just one test update needed for Windows (and a minor typo fix) then this should be good to go.

Thank you, after fixing up the test this is ready for review (and merge).

**Review by antross — APPROVED** [review]
