### PR TITLE
Fix: Prune UserConfig data

### LINKED ISSUE #2742: [Bug] Prune UserConfig data
Currently the CLI reports a `UserConfig` along with the `analyze` status. To help keep this anonymous it should be limited to known strings and enums (and automatically exclude new properties by default).

### PR DESCRIPTION
**Pull request by sarvaje**
Fix #2742

## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [x] Added/Updated related tests.

### CODE REVIEW

File: packages/hint/src/lib/cli/analyze.ts [hunk 1]
```diff
@@ -77,6 +77,34 @@ or set the flag --tracking=on|off`;
...
+    const result = {} as HintsConfigObject;
+
+    for (const [hintId, severity] of Object.entries(hints)) {
+        result[hintId] = typeof severity === 'string' ? severity : (severity as [HintSeverity, any])[0];
+    }
+
+    return result;
+};
+
+const pruneUserConfig = (userConfig: UserConfig) => {
```
Comment (antross) [inline packages/hint/src/lib/cli/analyze.ts]: Judging from the test failures, I think `userConfig` can be `undefined` here
```suggestion
const pruneUserConfig = (userConfig?: UserConfig) => {
    if (!userConfig) {
        return userConfig;
    }
```

Comment (sarvaje) [reply packages/hint/src/lib/cli/analyze.ts]: That's not the problem, it is userConfig.connector the one that can be undefined. I already have the fix in my pc, but I didn't update it, because there is a coverage problem.

According to the code, userConfig shouldn't be `undefined` at this point.

File: packages/hint/tests/lib/cli/analyze.ts [hunk 2]
```diff
@@ -409,3 +421,42 @@ test('If no sites are defined, it should return false', async (t) => {
 
     t.false(result);
 });
+
+test('If there is no errors analyzing the url, and it is the second time running a scan, and the user confirm telemetry, telemetry should be enabled', async (t) => {
```
Comment (antross) [inline packages/hint/tests/lib/cli/analyze.ts]: Can you also add another test to validate the handling of the `hints` section of the `userConfig`?

File: packages/hint/src/lib/cli/analyze.ts [hunk 3]
```diff
@@ -77,6 +78,57 @@ or set the flag --tracking=on|off`;
...
+    }
+
+    return result;
+};
+
+const getHintsFromConfiguration = (configName: string, parentConfigs: string[] = []) => {
+    try {
+        const configuration = loadConfiguration(configName, parentConfigs);
+
+        return { ...getHintsFromConfigurations(configuration.extends, [configName, ...parentConfigs]), ...getHintsForTelemetry(configuration.hints) }; // eslint-disable-line no-use-before-define,@typescript-eslint/no-use-before-define
```
Comment (antross) [inline packages/hint/src/lib/cli/analyze.ts]: To improve readability a touch:
```suggestion
        return {
            ...getHintsFromConfigurations(configuration.extends, [configName, ...parentConfigs]), // eslint-disable-line no-use-before-define,@typescript-eslint/no-use-before-define
            ...getHintsForTelemetry(configuration.hints)
        };
```

File: packages/hint/src/lib/cli/analyze.ts [hunk 4]
```diff
@@ -77,6 +78,57 @@ or set the flag --tracking=on|off`;
...
+};
+
+const getHintsFromConfigurations = (configurations?: string[], parentConfigs: string[] = [], index: number = 0): any => {
+    if (!configurations || configurations.length === 0) {
+        return {};
+    }
+
+    const config = configurations[0];
+
+    return { ...getHintsFromConfiguration(config, parentConfigs), ...getHintsFromConfigurations(configurations.slice(1), parentConfigs) };
```
Comment (antross) [inline packages/hint/src/lib/cli/analyze.ts]:
```suggestion
    return {
        ...getHintsFromConfiguration(config, parentConfigs),
        ...getHintsFromConfigurations(configurations.slice(1), parentConfigs)
    };
```

File: packages/hint/src/lib/cli/analyze.ts [hunk 5]
```diff
@@ -77,6 +78,57 @@ or set the flag --tracking=on|off`;
...
+    try {
+        const configuration = loadConfiguration(configName, parentConfigs);
+
+        return { ...getHintsFromConfigurations(configuration.extends, [configName, ...parentConfigs]), ...getHintsForTelemetry(configuration.hints) }; // eslint-disable-line no-use-before-define,@typescript-eslint/no-use-before-define
+    } catch (e) { // If the configuration doesn't exists, ignore it and returns an empty object.
+        return {};
+    }
+};
+
+const getHintsFromConfigurations = (configurations?: string[], parentConfigs: string[] = [], index: number = 0): any => {
```
Comment (antross) [inline packages/hint/src/lib/cli/analyze.ts]:
```suggestion
const getHintsFromConfigurations = (configurations?: string[], parentConfigs: string[] = [], index = 0): any => {
```

Comment (sarvaje) [reply packages/hint/src/lib/cli/analyze.ts]: In fact, the index is a leftover from debugging.

Comment (antross) [reply packages/hint/src/lib/cli/analyze.ts]: Clearly I didn't follow it far enough then 😂

**Comment by antross** [comment]
@utsavized One more for you here if you have time. We'll wear out your review button yet. 😊
