### PR TITLE
Fix: Icon purpose doesn't support combination of values

### LINKED ISSUE #3791: web manifest does not support combination of values for icon purpose
The commit that added support for `maskable` is https://github.com/webhintio/hint/commit/c5eb40f819f79b6f92b18dcd015bfda5807bb034#diff-07d179b4d8516fb968d006563b37bfe3

Unfortunately, as @amazingcaio it does not allow for combinations:

> I don't think this issue is fixed. `"purpose"` can have multiple valid values, so `"any maskable"` and `"maskable any"`, and (I suppose) even `"any maskable badge"` should also be accepted. I think the real issue here is, because the possible options are hardcoded you'd have to have all 15 different possibilities (cos you have to treat `"any maskable badge"` and `"ask badge maskable"` as different, for instance). I reckon having to type 15 different possible options is fine, but it gets more complicated as more values are added to the web manifest spec. If one more value is added, for instance, there would be 60 different possible combinations. So changing the code so you don't have to hardcode every option and disregard the order of the values (so `"any maskable"` and `"maskable any"` would be considered the same) is the best solution.

Need to find a way to enable this in the schema and our types.

_Note: Original issue text by @tmb-github is available in the history_

### PR DESCRIPTION
**Pull request by sarvaje**
Fix #3791

## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [x] Added/Updated related documentation.
- [x] Added/Updated related tests.

### CODE REVIEW

File: packages/hint-manifest-icons/src/hint.ts [hunk 1]
```diff
@@ -267,6 +269,32 @@ export default class ManifestIconHint implements IHint {
...
+                for (const purpose of purposesSet) {
+                    const index = purposes.indexOf(purpose);
+
+                    if (index >= 0) {
+                        purposes.splice(index, 1);
+                    }
+                }
+
+                if (purposes.length > 0) {
+                    // Is warning the right severity?
```
Comment (johnemau) [inline packages/hint-manifest-icons/src/hint.ts:292]: @molant

File: packages/hint-manifest-icons/src/hint.ts [hunk 2]
```diff
@@ -267,6 +269,32 @@ export default class ManifestIconHint implements IHint {
...
 
+        const validateIconsPurpose = (icons: ManifestImageResource[], resource: string, location: ProblemLocation | null) => {
+            for (let index = 0; index < icons.length; index++) {
+                const icon = icons[index];
+
+                if (!icon.purpose) {
+                    continue;
+                }
+
+                const purposes = compact(icon.purpose.split(' '));
```
Comment (johnemau) [inline packages/hint-manifest-icons/src/hint.ts:280]: IMO it would be better to avoid pulling in `lodash`

```js
const purposes = icon.purpose.split(' ').filter(i => i);
```

File: packages/hint-manifest-icons/package.json [hunk 3]
```diff
@@ -14,7 +14,8 @@
     "@hint/utils-i18n": "^1.0.3",
     "@hint/utils-types": "^1.0.1",
     "image-size": "^0.8.3",
-    "image-type": "^4.1.0"
+    "image-type": "^4.1.0",
+    "lodash": "^4.17.15"
```
Comment (johnemau) [inline packages/hint-manifest-icons/package.json:18]: IMO we should avoid adding dependencies when possible. I think we can get away without lodash for this change.

File: packages/hint-manifest-icons/src/hint.ts [hunk 4]
```diff
@@ -302,6 +332,24 @@ export default class ManifestIconHint implements IHint {
...
 
+        const invalidManifest = ({ errors, resource }: ManifestInvalidSchema) => {
+            for (const error of errors) {
+                const isIconError = error.dataPath.match(iconsErrorRegex);
+
+                if (isIconError) {
+                    // Is error the right severity?
+                    const message = getMessage('iconPurposeInvalid', context.language, isIconError[1]);
+
+                    console.log(message);
```
Comment (johnemau) [inline packages/hint-manifest-icons/src/hint.ts:343]: Is this console.log left over from debugging?

File: packages/hint-manifest-icons/src/hint.ts [hunk 5]
```diff
@@ -6,16 +6,18 @@ import { imageSize as getImageData } from 'image-size';
...
 import { debug as d } from '@hint/utils-debug';
 import { determineMediaTypeBasedOnFileExtension } from '@hint/utils/dist/src/content-type';
+import compact = require('lodash/compact');
 
 import meta from './meta';
 import { getMessage } from './i18n.import';
 import { extname } from 'path';
 
 const debug: debug.IDebugger = d(__filename);
+const iconsErrorRegex: RegExp = /\.icons\[\d\]\.(purpose)/i;
```
Comment (johnemau) [inline packages/hint-manifest-icons/src/hint.ts:20]: Please include a comment with an example error message you expect this regex to match.
```js
// example: manifest.icons9.purpose

File: packages/hint-manifest-icons/src/hint.ts [hunk 6]
```diff
@@ -267,6 +269,32 @@ export default class ManifestIconHint implements IHint {
             return validSizes;
         };
 
+        const validateIconsPurpose = (icons: ManifestImageResource[], resource: string, location: ProblemLocation | null) => {
+            for (let index = 0; index < icons.length; index++) {
```
Comment (johnemau) [inline packages/hint-manifest-icons/src/hint.ts:273]: nit: suggest using `for of` to avoid shadowing the below `index` variable.

File: packages/hint-manifest-icons/src/hint.ts [hunk 7]
```diff
@@ -302,6 +332,24 @@ export default class ManifestIconHint implements IHint {
             }
         };
 
+        const invalidManifest = ({ errors, resource }: ManifestInvalidSchema) => {
+            for (const error of errors) {
+                const isIconError = error.dataPath.match(iconsErrorRegex);
+
+                if (isIconError) {
+                    // Is error the right severity?
```
Comment (johnemau) [inline packages/hint-manifest-icons/src/hint.ts:340]: @molant

File: packages/parser-manifest/src/schema.json [hunk 8]
```diff
@@ -10,13 +10,7 @@
...
                 "purpose": {
                     "default": "any",
-                    "enum": [
-                        "any",
-                        "any badge",
-                        "badge",
-                        "badge any",
-                        "maskable"
-                    ],
+                    "pattern": "^\\s*(any|maskable|badge)(\\s+(any|maskable|badge)?)*$",
```
Comment (johnemau) [inline packages/parser-manifest/src/schema.json:13]: https://github.com/webhintio/hint/issues/3791#issuecomment-641935207

We need to add support for `monochrome` as well, I am OK if you think that should be done in a follow-up change.

File: packages/hint-manifest-icons/src/hint.ts (hunk 4 above)
Comment (sarvaje) [reply packages/hint-manifest-icons/src/hint.ts:343]: yes! Good catch

File: packages/parser-manifest/src/schema.json (hunk 8 above)
Comment (sarvaje) [reply packages/parser-manifest/src/schema.json:13]: I can add it to this PR

File: packages/hint-manifest-icons/src/hint.ts (hunk 2 above)
Comment (sarvaje) [reply packages/hint-manifest-icons/src/hint.ts:280]: > const purposes = icon.purpose.split(' ').filter(i => i);

I like that!

File: packages/hint-manifest-icons/src/hint.ts [hunk 9]
```diff
@@ -267,6 +269,32 @@ export default class ManifestIconHint implements IHint {
...
+                    const index = purposes.indexOf(purpose);
+
+                    if (index >= 0) {
+                        purposes.splice(index, 1);
+                    }
+                }
+
+                if (purposes.length > 0) {
+                    // Is warning the right severity?
+                    context.report(resource, getMessage('iconPurposeDuplicate', context.language, [...(new Set(purposes))].join(' ')), { location, severity: Severity.warning });
```
Comment (molant) [inline packages/hint-manifest-icons/src/hint.ts:298]: We might even want to lower the severity and mark it as a hint. Having a valid duplicate purpose doesn't break anything.

File: packages/hint-manifest-icons/src/hint.ts [hunk 10]
```diff
@@ -302,6 +337,21 @@ export default class ManifestIconHint implements IHint {
             }
         };
 
+        const invalidManifest = ({ errors, resource }: ManifestInvalidSchema) => {
+            for (const error of errors) {
+                const isIconError = error.dataPath.match(iconsErrorRegex);
+
+                if (isIconError) {
+                    // Is error the right severity?
+                    context.report(resource, getMessage('iconPurposeInvalid', context.language, isIconError[1]), {
```
Comment (molant) [inline packages/hint-manifest-icons/src/hint.ts:346]: The [spec says the following](https://w3c.github.io/manifest/#purpose-member):

> If an icon contains multiple purposes, it could be used for any of those purposes. If none of the stated purposes are recognized, the icon is totally ignored. For example, if an icon has purpose "monochrome fizzbuzz", then it could be used as a monochrome icon, as "monochrome" is a valid purpose. However, if an icon just has the purpose "fizzbuzz", then it will be ignored.

That said, I think that we should have an Error if none of the purposes are recognized (the icon is not going to work so that's probably an error) and a warning otherwise.
We could maybe lower the severity one level for each but probably at that moment we will have to look at other icons and what they do, etc. which might complicate things a lot for not a lot of value.

@Malvoz what do you think?

File: packages/hint-manifest-icons/src/_locales/en/messages.json [hunk 11]
```diff
@@ -11,6 +11,14 @@
         "description": "Report message when an icon request return an status code !== 200",
         "message": "Icon could not be fetched (status code: $1)."
     },
+    "iconPurposeDuplicate": {
+        "description": "Report message when an icon has a duplicate value in the property purpose",
+        "message": "Duplicate value(s) '$1' found in icon purpose property."
```
Comment (molant) [inline packages/hint-manifest-icons/src/_locales/en/messages.json:16]: The convention is to use `$1` at the end so localization is easier.
@johnemau do you have any suggestions?

File: packages/hint-manifest-icons/src/_locales/en/messages.json [hunk 12]
```diff
@@ -11,6 +11,14 @@
...
+    },
+    "iconPurposeInvalid": {
+        "description": "Report message when an icon has an invalid value in the property purpose",
+        "message": "Invalid icon property $1."
```
Comment (molant) [inline packages/hint-manifest-icons/src/_locales/en/messages.json:20]:
```suggestion
        "message": "Invalid icon property: $1."
```

File: packages/hint-manifest-icons/src/hint.ts (hunk 10 above)
Comment (sarvaje) [reply packages/hint-manifest-icons/src/hint.ts:346]: If having an invalid value "is not a problem" we should modify the schema to support an string, and do all the checks in the hint.

File: packages/hint-manifest-icons/src/_locales/en/messages.json (hunk 11 above)
Comment (sarvaje) [reply packages/hint-manifest-icons/src/_locales/en/messages.json:16]: what about `Duplicate value(s) found in icon purpose porperty: $1`?

Comment (molant) [reply packages/hint-manifest-icons/src/_locales/en/messages.json:16]: SGTM

File: packages/hint-manifest-icons/src/hint.ts (hunk 10 above)
Comment (molant) [reply packages/hint-manifest-icons/src/hint.ts:346]: That's what the spec says so...

Comment (sarvaje) [reply packages/hint-manifest-icons/src/hint.ts:346]: Ok, I will:

1. Remove the regex from the schema.
2. Check if any value is invalid.
3. In case any value is invalid, report a warning.

> We could maybe lower the severity one level for each but probably at that moment we will have to look at other icons and what they do, etc. which might complicate things a lot for not a lot of value.

If you mean the other icons in the list of icons, I think we should report what we found in each icon independently.

File: packages/hint-manifest-icons/src/hint.ts [hunk 13]
```diff
@@ -267,6 +270,43 @@ export default class ManifestIconHint implements IHint {
             return validSizes;
         };
 
+        const validateIconsPurpose = (icons: ManifestImageResource[], resource: string, getLocation: JSONLocationFunction) => {
```
Comment (molant) [inline packages/hint-manifest-icons/src/hint.ts:273]:
```suggestion

        // See https://w3c.github.io/manifest/#purpose-member
        const validateIconsPurpose = (icons: ManifestImageResource[], resource: string, getLocation: JSONLocationFunction) => {
```

File: packages/hint-manifest-icons/src/hint.ts [hunk 14]
```diff
@@ -267,6 +270,43 @@ export default class ManifestIconHint implements IHint {
...
+            for (let iconIndex = 0; iconIndex < icons.length; iconIndex++) {
+                const icon = icons[iconIndex];
+
+                if (!icon.purpose) {
+                    continue;
+                }
+
+                const purposes = icon.purpose.split(' ').filter((purpose) => {
+                    return purpose;
+                });
```
Comment (molant) [inline packages/hint-manifest-icons/src/hint.ts:283]: Is this `filter` to remove any possible trailing space? For example, if the purpose is `maskable badge `?
If so I think it will be more readable if you just do this:

```suggestion
                const purposes = icon.purpose.trim().split(' ');
```

File: packages/hint-manifest-icons/src/hint.ts [hunk 15]
```diff
@@ -267,6 +270,43 @@ export default class ManifestIconHint implements IHint {
...
+                    }
+
+                    const purposeIndex = purposes.indexOf(purpose);
+
+                    if (purposeIndex >= 0) {
+                        purposes.splice(purposeIndex, 1);
+                    }
+                }
+
+                if (purposes.length > 0) {
```
Comment (molant) [inline packages/hint-manifest-icons/src/hint.ts:301]: It took me a bit to figure out what you were doing in here and why `purposes.length` had to be 0 by line 301.

What do you think of instead doing this:

```suggestion                    
                }

                if (purposes.length !== purposesSet.size) {
```

File: packages/hint-manifest-icons/tests/tests.ts [hunk 16]
```diff
@@ -214,7 +214,123 @@ const tests: HintTest[] = [
...
+                    }`
+            }
+        }
+    },
+    {
+        name: 'Duplicated purpose found',
+        reports: [
+            {
+                message: `Duplicate value(s) found in icon purpose porperty: any.`,
+                position: {
```
Comment (molant) [inline packages/hint-manifest-icons/tests/tests.ts:227]: Maybe we could use the position matching so this is easier to maintain in the future?

File: packages/hint-manifest-icons/src/hint.ts (hunk 14 above)
Comment (sarvaje) [reply packages/hint-manifest-icons/src/hint.ts:283]: It is also to remove possible extra spaces in the middle of the string: `any       badge`

File: packages/hint-manifest-icons/src/hint.ts (hunk 15 above)
Comment (sarvaje) [reply packages/hint-manifest-icons/src/hint.ts:302]: That was my first solution, but you can't know the duplicated items with that code. Maybe I can add a few comments?

File: packages/hint-manifest-icons/tests/tests.ts (hunk 16 above)
Comment (sarvaje) [reply packages/hint-manifest-icons/tests/tests.ts:227]: That would be awesome, but does it work with this match `icons[0].purpose` because I think I tried and it didn't work. (I am going take another look)

Comment (sarvaje) [reply packages/hint-manifest-icons/tests/tests.ts:227]: I think I can use `purpose` for the match, but it will only match the first occurrence of `purpose` and there are 3 icons in the tests.

File: packages/hint-manifest-icons/src/hint.ts [hunk 17]
```diff
@@ -17,6 +17,9 @@ import { extname } from 'path';
 
 const debug: debug.IDebugger = d(__filename);
 
+// Valid values for icon purpose property.
+const validPurposes = ['any', 'maskable', 'badge', 'monochrome'];
```
Comment (amazingcaio) [inline packages/hint-manifest-icons/src/hint.ts:21]: as w3c/manifest#833 has been merged, the spec does not mention `badge` any more, so i think it should be removed from `validPurposes`, though maybe there should be a different issue dealing with this? (especially because you might want webhint to have a specific behaviour, like warning `badge` was replaced?)

Comment (molant) [reply packages/hint-manifest-icons/src/hint.ts:21]: @sarvaje @hxlnt this hint is still not [published "officially"](https://github.com/webhintio/hint/blob/145ab5a11f7077a63b28a954f9a45bc5efa20e9b/packages/hint-manifest-icons/package.json#L55) although it seems we are using it seems to be active in different places. IIRC the missing piece was to update the documentation. Ideally we should do the `badge/monochrome` before we "release" it.

https://github.com/w3c/manifest/pull/833#issuecomment-645756918

> Confirmed that Chrome does not use purpose: badge anywhere, including on the server-side infrastructure. From our perspective, we are good to rename it and change its semantics. LGTM.

@amazingcaio, thanks for catching this change!

File: packages/hint-manifest-icons/tests/tests.ts (hunk 16 above)
Comment (molant) [reply packages/hint-manifest-icons/tests/tests.ts:227]: I thought it was a bit more flexible. Not worth doing it then.

File: packages/hint-manifest-icons/src/hint.ts (hunk 14 above)
Comment (molant) [reply packages/hint-manifest-icons/src/hint.ts:284]: The following should work but at this time I'm not sure what's easier to read

```suggestion
                const purposes = icon.purpose.trim().replace(/\s\s*/g,' ').split(' ').;
```

@johnemau what do you think?

Comment (sarvaje) [reply packages/hint-manifest-icons/src/hint.ts:284]: for readability, I think the regex is easy and more clear what we are doing. Performance wise, I'm not sure what is better.

Comment (molant) [reply packages/hint-manifest-icons/src/hint.ts:284]: Let's optimize for readability then, I don't think we can really measure the impact of one or the other 😊

File: packages/hint-manifest-icons/src/hint.ts (hunk 15 above)
Comment (molant) [reply packages/hint-manifest-icons/src/hint.ts]: I think it might be we are doing things in 2 different places.

What about filtering/finding duplicated in the same place?

```ts
if (purposes.length !== purposesSet.size) {
  // Check if it's duplicated here and report
}
```

That way if we want to refactor that code into another function we can. We might have to do an extra loop but it should be negligible and make it better to read/maintain.

File: packages/hint-manifest-icons/src/hint.ts (hunk 17 above)
Comment (sarvaje) [reply packages/hint-manifest-icons/src/hint.ts]: Thanks @amazingcaio!

Comment (amazingcaio) [reply packages/hint-manifest-icons/src/hint.ts]: no problem. also, there were a couple of places where you misspelt `property` as `porperty`. you may want to fix that :)

Comment (sarvaje) [reply packages/hint-manifest-icons/src/hint.ts]: Thanks!! It should be fixed now.

File: packages/hint-manifest-icons/src/_locales/en/messages.json [hunk 18]
```diff
@@ -11,6 +11,14 @@
         "description": "Report message when an icon request return an status code !== 200",
         "message": "Icon could not be fetched (status code: $1)."
     },
+    "iconPurposeDuplicate": {
+        "description": "Report message when an icon has a duplicate value in the property purpose",
+        "message": "Duplicate value(s) found in icon purpose porperty: $1."
```
Comment (amazingcaio) [inline packages/hint-manifest-icons/src/_locales/en/messages.json:16]: missed misspelling
```suggestion
        "message": "Duplicate value(s) found in icon purpose property: $1."
```

File: packages/hint-manifest-icons/tests/tests.ts [hunk 19]
```diff
@@ -214,7 +214,123 @@ const tests: HintTest[] = [
...
                                 "type": "image/png"
                             }
-                            ]
+                        ]
+                    }`
+            }
+        }
+    },
+    {
+        name: 'Duplicated purpose found',
```
Comment (amazingcaio) [inline packages/hint-manifest-icons/tests/tests.ts:223]: sorry for being so pedantic
```suggestion
        name: 'Duplicate purpose found',
```

File: packages/hint-manifest-icons/src/hint.ts (hunk 14 above)
Comment (sarvaje) [reply packages/hint-manifest-icons/src/hint.ts]: done

File: packages/hint-manifest-icons/src/hint.ts (hunk 15 above)
Comment (sarvaje) [reply packages/hint-manifest-icons/src/hint.ts]: done

File: packages/hint-manifest-icons/tests/tests.ts (hunk 19 above)
Comment (sarvaje) [reply packages/hint-manifest-icons/tests/tests.ts:223]: 🤦‍♂️I forgot to save the change before pushing... 
image

File: packages/hint-manifest-icons/src/_locales/en/messages.json (hunk 18 above)
Comment (sarvaje) [reply packages/hint-manifest-icons/src/_locales/en/messages.json]: 🤦‍♂️ I forgot to save my changes before pushing...
image

File: packages/hint-manifest-icons/tests/tests.ts (hunk 19 above)
Comment (molant) [reply packages/hint-manifest-icons/tests/tests.ts]: English isn't @sarvaje's nor mine first language so any grammar, spelling, or style corrections are more than welcome 😊

Thanks a lot!

Comment (sarvaje) [reply packages/hint-manifest-icons/tests/tests.ts]: Thanks for the correction!!, as @molant says, English isn't our first language :)

File: packages/hint-manifest-icons/src/hint.ts [hunk 20]
```diff
@@ -267,6 +270,78 @@ export default class ManifestIconHint implements IHint {
...
+            for (const purpose of purposes) {
+                // Check if the purpose is valid.
+                if (!validPurposes.includes(purpose)) {
+                    context.report(resource, getMessage('iconPurposeInvalid', context.language, purpose), {
+                        location: getLocation(`icons[${iconIndex}].purpose`),
+                        severity: Severity.warning
+                    });
+                }
+            }
+            console.log(iconIndex);
```
Comment (molant) [inline packages/hint-manifest-icons/src/hint.ts:283]:
```suggestion
```

File: packages/hint-manifest-icons/src/hint.ts [hunk 21]
```diff
@@ -267,6 +270,78 @@ export default class ManifestIconHint implements IHint {
...
+            if (purposesCopy.length > 0) {
+                context.report(resource, getMessage('iconPurposeDuplicate', context.language, [...(new Set(purposesCopy))].join(' ')), {
+                    location: getLocation(`icons[${iconIndex}].purpose`),
+                    severity: Severity.hint
+                });
+            }
+
+            console.log(getMessage('iconPurposeDuplicate', context.language, [...(new Set(purposesCopy))].join(' ')));
+            console.log(getLocation(`icons[${iconIndex}].purpose`));
+            console.log(iconIndex);
```
Comment (molant) [inline packages/hint-manifest-icons/src/hint.ts:320]: Are this leftovers or did you intend to use `debug` instead?

Comment (sarvaje) [reply packages/hint-manifest-icons/src/hint.ts:320]: Sorry, I forgot to remove the `console.log`s

Comment (sarvaje) [reply packages/hint-manifest-icons/src/hint.ts]: done!

File: packages/hint-manifest-icons/tests/tests.ts (hunk 19 above)
Comment (amazingcaio) [reply packages/hint-manifest-icons/tests/tests.ts]: english isn't my first language either lol. the correction was more about consistency, as `duplicate` was used in other cases, not `duplicated`. (plus `duplicate` does sound better in my ears, but english is my second language so i'm not that reliable.)

**Comment by molant** [comment]
@sarvaje is this ready for another review?

**Comment by sarvaje** [comment]
> @sarvaje is this ready for another review?

@molant Yes, everything should be addressed

**Comment by antross** [comment]
@molant any further feedback on this or is it good to merge?

**Comment by molant** [comment]
Don't think I'll have the time to check until next week. If it's OK on your side then go ahead 😊

File: packages/hint-manifest-icons/src/hint.ts [hunk 22]
```diff
@@ -267,6 +270,73 @@ export default class ManifestIconHint implements IHint {
...
+                    continue;
+                }
+
+                /*
+                 * Remove unnecessary empty spaces before split the array.
+                 */
+                const purposes = icon.purpose
+                    .trim()
+                    .replace(/\s\s*/g, ' ')
+                    .split(' ');
```
Comment (antross) [inline packages/hint-manifest-icons/src/hint.ts:333]: We can just pass the regex to `split` directly.
```suggestion
                    .split(/\s\s*/g);
```

File: packages/hint-manifest-icons/src/hint.ts [hunk 23]
```diff
@@ -267,6 +270,73 @@ export default class ManifestIconHint implements IHint {
...
+                    purposesCopy.splice(purposeIndex, 1);
+                }
+            }
+
+            /*
+             * Check if purposesCopy contains any purpose, if so, those
+             * items are duplicated.
+             */
+            if (purposesCopy.length > 0) {
+                context.report(resource, getMessage('iconPurposeDuplicate', context.language, [...(new Set(purposesCopy))].join(' ')), {
```
Comment (antross) [inline packages/hint-manifest-icons/src/hint.ts:311]: Probably should comma-separate these:
```suggestion
                context.report(resource, getMessage('iconPurposeDuplicate', context.language, [...(new Set(purposesCopy))].join(', ')), {
```

File: packages/hint-manifest-icons/src/hint.ts [hunk 24]
```diff
@@ -277,13 +347,15 @@ export default class ManifestIconHint implements IHint {
                 if (icons.length > 0) {
 
                     debug(`Validating if manifest-icon file exists`);
-                    const validSizes = await validateIcons(icons, hostnameWithProtocol, resource, getLocation);
+                    const validSizes = await validateIconsSize(icons, hostnameWithProtocol, resource, getLocation);
+                    const iconlocation = getLocation('icons');
 
                     if (validSizes.length > 0) {
-                        const iconlocation = getLocation('icons');
```
Comment (antross) [inline packages/hint-manifest-icons/src/hint.ts:283]: Seems like this isn't used outside this block, so can probably be kept here rather than moved out.

File: packages/hint-manifest-icons/tests/tests.ts (hunk 16 above)
Comment (antross) [reply packages/hint-manifest-icons/tests/tests.ts:227]: The position matching should work here, we just need to include enough of the matching line to be unique within the file.
