### PR TITLE
Fix: Location for json errors

### LINKED ISSUE #2037: [Bug] Bad location for compilerOptions reports in tsconfig rules
image

### LINKED ISSUE #2222: [Feature] Point to `compilerOptions` in tsconfig.json for missing options
Currently missing options like `compilerOptions.importHelpers` just point to the start of the file. If `compilerOptions` is present, pointing to it would provide more local and useful feedback.

This is most noticeable in the vscode extension.

### PR DESCRIPTION
**Pull request by sarvaje**
Fix #2222
Fix #2037

## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [x] Added/Updated related documentation.
- [x] Added/Updated related tests.

### CODE REVIEW

**Comment by molant** [comment]
@sarvaje tests related to `extends` seem to be failing

File: packages/utils/src/json-parser.ts [hunk 1]
```diff
@@ -27,7 +27,13 @@ class JSONResult implements IJSONResult {
...
     public getLocation(path: string, options?: IJSONLocationOptions): ProblemLocation | null {
         const segments = this.pathToSegments(path);
-        const node = findNodeAtLocation(this._root, segments) || null;
+        let node = null;
+
+        while (!node && segments.length > 0) {
+            node = findNodeAtLocation(this._root, segments) || null;
+
+            segments.pop();
+        }
```
Comment (molant) [inline packages/utils/src/json-parser.ts]: I'm working on something similar (making sure the typescript errors point to the wrong values and not the property names)  and with your change and my change we are pointing to the opening `{` instead of the property name when it's missing:

image

I'll look into this but I'll probably open a PR that supersedes this one.

Comment (molant) [reply packages/utils/src/json-parser.ts]: Got it working. This is my code:

```js
         while (!node && segments.length > 0) {
            node = findNodeAtLocation(this._root, segments) || null;

            if (!node) {
                missing = true;
            }

            segments.pop();
        }

        /**
         * If the property is missing but its ancestor is present we want to report
         * the property name and not the value (which will be an opening `{` ).
         */
        if (node && missing && options && options.at === 'value') {
            return this.offsetToLocation(this.getAdjustedOffset(node, path));
        }

        /**
         * The node isn't in the current file. Use alternative path if provided. This happens
         * when extending configurations.
         */
        if (!node && this._alternatePath && path !== this._alternatePath) {
            return this.getLocation(this._alternatePath, options);
        }
```

If we are OK with your PR I'm thinking about cherry-picking to preserve the history and the author. @antross @sarvaje what do you think?

Comment (sarvaje) [reply packages/utils/src/json-parser.ts]: Do I need to touch something?

Comment (molant) [reply packages/utils/src/json-parser.ts]: Don't think so. Depends on how we want to merge all of this. My code depends on yours so we could have just one PR with all the changes or a couple. Either way, can we wait until I release the new version of `create-hint` before merging anything else?

Comment (antross) [reply packages/utils/src/json-parser.ts]: New version of `create-hint` has been released. Discussed with @molant and we're okay merging this PR as-is then he can rebase his work on top of it.
