### PR TITLE
Fix: Discover tslib in projects with nested structure

### LINKED ISSUE #4175: [Bug] Couldn't find package "tslib" error in a nested project structure
# 🐛 Bug report

## Description

I am working on a frontend that had the expected structure with tsconfig.json at the root of the project, no error was reported.

Now the frontend was integrated as git submodule within a project with a nested folder structure and I always get the error:
```
Couldn't find package "tslib".
(typescript-config/import-helpers)
```

This error pops up even though `tslib` is installed (v2.0.3) and `importHelpers: true` is enabled in the `tsconfig.json`

## Environment

* __`hint` version:__  1.5.9 (VSCode)
* __`Node.js` version:__  v14.12.0
* __`OS`:__  Ubuntu

### PR DESCRIPTION
**Pull request by mhatvan**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [ ] Added/Updated related tests.

## Short description of the change(s)
Change pathToTslib to resolve the path to tslib based on the tsconfig.json location rather than current working directory. Fixes #4175.

### CODE REVIEW

File: packages/hint-typescript-config/src/import-helpers.ts [hunk 1]
```diff
@@ -33,7 +33,7 @@ export default class TypeScriptConfigImportHelpers implements IHint {
         const validateTslibInstalled = (evt: ScanEnd) => {
             const { resource } = evt;
 
-            const pathToTslib = path.join(process.cwd(), 'node_modules', 'tslib');
+            const pathToTslib = path.dirname(require.resolve('tslib', { paths: [resource] }));
```
Comment (antross) [inline packages/hint-typescript-config/src/import-helpers.ts:36]: If I recall correctly `require.resolve` will throw if `tslib` can't be found, so we should probably move this line inside the `try/catch` block.

File: packages/hint-typescript-config/src/import-helpers.ts [hunk 2]
```diff
@@ -33,7 +33,7 @@ export default class TypeScriptConfigImportHelpers implements IHint {
...
 
             debug(`Searching "tslib" in ${pathToTslib}`);
```
Comment (antross) [inline packages/hint-typescript-config/src/import-helpers.ts:38]: Since we won't have the full path unless `require.resolve` succeeds (and we'll be moving that below to the try/catch), I think we can still make this debug statement useful by updating it to say we're searching for tslib "relative to ${resource}".

**Review by antross — COMMENTED** [review]
Thanks for putting this together @mhatvan! 

I just noticed a couple of minor tweaks we'll probably want to make, then I think this will be ready to go.

**Comment by mhatvan** [comment]
@antross I totally missed the PR review comments, I updated the code accordingly!

**Review by antross — APPROVED** [review]
LGTM, thanks for the update @mhatvan!

@sarvaje want to give this a quick look before merging?

**Review by sarvaje — APPROVED** [review]
LGTM!
