### PR TITLE
Fix: Change 'boxen' import and remove '@types/boxen'

### LINKED ISSUE #2036: [Bug] Change how `boxen` is imported and remove `@types/boxen`
`boxen` has now types included OOB. We should remove the `@types/boxen` from dependencies and use `import boxen from 'boxen'` instead of  `require('boxen')`.

### PR DESCRIPTION
**Pull request by karansapolia**
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Fix #2036

## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- ~~[ ] Added/Updated related documentation.~~
- ~~[ ] Added/Updated related tests.~~

## Short description of the change(s)
Changes how `boxen` is imported and removes `@types/boxen`.
Follow up to #1943.

### CODE REVIEW

File: packages/hint/src/lib/cli/analyze.ts [hunk 1]
```diff
@@ -22,8 +22,8 @@ import { installPackages } from '../utils/npm';
 import * as insights from '../utils/app-insights';
 import { FormatterOptions, IFormatter } from '../types/formatters';
 import loadHintPackage from '../utils/packages/load-hint-package';
+import boxen from 'boxen';
```
Comment (antross) [inline packages/hint/src/lib/cli/analyze.ts]: Let's move this up to the group of imports coming from other packages (after `import * as async from 'async';`).

Comment (karansapolia) [reply packages/hint/src/lib/cli/analyze.ts]: Right! let me do that

**Comment by molant** [comment]
Thanks @karansapolia !
