### PR TITLE
Fix: Wrap some JSX expressions placeholders in list items

### LINKED ISSUE #3486: [Bug] JSX: <ul> must only directly contain <li> wrongly detected
# 🐛 Bug report

## Description

`webhint` VSCode plugin shows error for ul/li if li-s are generated with code:

image

## Environment

* __`hint` version:__ v6.0.3
* __`Node.js` version:__ v12.11.1
* __`OS`:__ macOS Mojave 10.14.6
* __URL for which webhint failed:__ n/a

## `webhint` configuration

Default configuration.

### PR DESCRIPTION
**Pull request by johnemau**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [x] Added/Updated related tests.

## Short description of the change(s)
This changes follows [the recommendation][1] from @antross to wrap the `{expression}` placeholders parented to lists (`<ul>/<ol>`) in list items `<li>`.

This avoids a false-positive hint failure that the lists contain non-list items.

[1]: https://github.com/webhintio/hint/issues/3486#issuecomment-592649518

Fixes #3486

### CODE REVIEW

**Comment by johnemau** [comment]
@antross I was unable to get a VSIX package to test the vscode extension locally. Any suggestions on how to bundle the `hint` package directly in the VSIX package?

File: packages/parser-jsx/tests/tests.ts [hunk 1]
```diff
@@ -147,6 +147,20 @@ test('It replaces expressions with text placeholders', async (t) => {
     t.is(div.innerHTML, '{expression}');
 });
 
+test('It wraps expression placeholder text with <li> when parented to <ul>', async (t) => {
+    const { document } = await parseJSX(`const jsx = <ul>{myText}</ul>;`);
+    const div = document.querySelectorAll('ul')[0];
```
Comment (johnemau) [inline packages/parser-jsx/tests/tests.ts:152]: I will change this `div` to `ul` and similar with the `ol` test.

**Comment by johnemau** [comment]
Thanks for the feedback on testing, I confirmed this fixes the issue.

ext-fix

File: packages/parser-jsx/src/parser.ts [hunk 2]
```diff
@@ -206,6 +206,52 @@ const addChild = (data: ElementData | TextData, parent: JSXElement, children: Ch
     children.set(parent, list);
 };
 
+/**
+ * Is the node a list container (`<ul>/<ol>`).
+ */
+const isListNode = (node: JSXElement | JSXAttribute | undefined): node is JSXElement => {
```
Comment (antross) [inline packages/parser-jsx/src/parser.ts:212]: Minor nit, not blocking.
```suggestion
const isListNode = (node?: JSXElement | JSXAttribute): node is JSXElement => {
```

Comment (johnemau) [reply packages/parser-jsx/src/parser.ts]: Thanks, done!
