### PR TITLE
Fix: Don't allow Breaking commits to span multiple packages

### LINKED ISSUE #2415: [Feature] Don't allow Breaking commits to span multiple packages
To be implemented as a pre-commit hook. Possibly allowing some sort of flag in the commit message to override.

This should help us avoid accidentally bumping the major version number of dependent packages (e.g. hints) that need updated when we make a breaking change to one of their dependencies (e.g. parsers).

### PR DESCRIPTION
**Pull request by sarvaje**
Fix #2415

## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

### CODE REVIEW

File: scripts/check-commit-message.js [hunk 1]
```diff
@@ -106,6 +106,36 @@ const checkSecoundLine = (line) => {
...
+
+        if (pathParts[0] === 'packages') {
+            pkgs.add(pathParts[1]);
+        }
+
+        return pkgs;
+    }, new Set());
+
+    if (packages.size > 1) {
+        issues.push(`[Line 1] A breaking change cannot affect to more than one package. Packages affected:\n    - ${[...packages].join('\n    - ')}`);
```
Comment (antross) [inline scripts/check-commit-message.js]: The `[Line 1]` is used to refer to the first line of the commit message. Given we're not technically validating the message itself I think we should omit that here.

```suggestion
        issues.push(`A breaking change cannot affect to more than one package. Packages affected:\n    - ${[...packages].join('\n    - ')}`);
```

**Comment by sarvaje** [comment]
@antross done!
