### PR TITLE
Build: Fix code coverage report

### LINKED ISSUE #2309: [Bug] No code coverage report
Looks like we aren't getting any code coverage output. Need to find out when we broke:

```
11 tests passed
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
Done in 39.82s.
```

So far @antross and my self are reproducing this

### PR DESCRIPTION
**Pull request by molant**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- ~~Added/Updated related documentation.~~
- ~~Added/Updated related tests.~~

## Short description of the change(s)

Fix #2309

### CODE REVIEW

**Comment by antross** [comment]
@molant I tried this locally and still didn't get any coverage reported. 😕

**Comment by molant** [comment]
Looks like the package `hint` doesn't pass the threshold 😞

**Comment by molant** [comment]
The problem seems to be with `json-parser`:
image

I'm going to ignore that file and open an issue to add tests but I wonder if we should move it to the `utils`  package. @antross ?

**Comment by antross** [comment]
> but I wonder if we should move it to the utils package.

Yeah, moving it to utils makes sense to me.

**Comment by molant** [comment]
Code coverage is different in CI than locally 😭
Moving to `utils`  will be a breaking so we should probably do it now...

**Comment by molant** [comment]
@antross this is ready for review.

File: packages/utils/src/types/json-parser.ts [hunk 1]
```diff
@@ -1,4 +1,4 @@
-import { ProblemLocation } from './problems';
+import { ProblemLocation } from './problem-location';
 
 export interface IJSONLocationOptions {
```
Comment (antross) [inline packages/utils/src/types/json-parser.ts]: Not blocking for this PR, but what do you think about starting to group types with util implementation instead of in a separate folder? E.g. having a `src/json` folder with `parser` and `types`?

Comment (molant) [reply packages/utils/src/types/json-parser.ts]: SGTM, we will have to maintain both things until the next breaking.

Comment (antross) [reply packages/utils/src/types/json-parser.ts]: Yeah, I'd probably hold off on doing it at all until the next breaking opportunity.
