### PR TITLE
Fix: Check for localStorage availability

### LINKED ISSUE #3494: [Bug] Chrome extension fails to read `localStorage` when 3p cookies are disabled.
# 🐛 Bug report

## Description

Extension does not work [when third-party cookies are blocked](https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document) in Chrome (79.0.3945.130):

`Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.`

webhint-not-working-if-3p-cookies-disallowed

## Environment

* __webhint version:__ 2.0.1

<hr>

This issue should ultimately be solved on Chrome's side, see: https://bugs.chromium.org/p/chromium/issues/detail?id=971848

### PR DESCRIPTION
**Pull request by Hirse**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [ ] Added/Updated related tests.

## Short description of the change(s)

Fall back to non-persistent in-memory cache if `localStorage` is not available.
Fixes #3494

chromium: [webhint-2.0.3.zip](https://github.com/webhintio/hint/files/4172602/webhint-2.0.3.zip)

### CODE REVIEW

File: packages/extension-browser/src/devtools/utils/storage.ts [hunk 1]
```diff
@@ -1,6 +1,30 @@
+let storage: {
+    getItem(key: string): string | null;
+    setItem(key: string, value: string): void;
+};
```
Comment (antross) [inline packages/extension-browser/src/devtools/utils/storage.ts]: Let's pull the signatures from the built-in `Storage` type, but still scoped to just the methods we want.
```suggestion
let storage: Pick<Storage, 'getItem' | 'setItem'>;
```

File: packages/extension-browser/src/devtools/utils/storage.ts [hunk 2]
```diff
@@ -1,6 +1,30 @@
...
+
+try {
+    storage = {
+        getItem: localStorage.getItem.bind(localStorage),
+        setItem: localStorage.setItem.bind(localStorage)
+    };
+} catch (error) {
+    console.warn(`LocalStorage not available, falling back to in-memory storage: ${error}`);
+    const cache = new Map<string, string>();
```
Comment (antross) [inline packages/extension-browser/src/devtools/utils/storage.ts]: We'll know for sure once CI finishes, but I think our linter is configured to require a new line before `const`.
```suggestion

    const cache = new Map<string, string>();
```

File: packages/extension-browser/src/devtools/utils/storage.ts (hunk 1 above)
Comment (Hirse) [reply packages/extension-browser/src/devtools/utils/storage.ts]: Didn't know `Pick` before. This is awesome.

File: packages/extension-browser/src/devtools/utils/storage.ts (hunk 2 above)
Comment (Hirse) [reply packages/extension-browser/src/devtools/utils/storage.ts]: ESLint doesn't complain and it doesn't seem to need one here:
https://github.com/webhintio/hint/blob/98861bac7336d535ae100d680497a01e9ad3113a/packages/extension-browser/src/devtools/utils/storage.ts#L2-L3

Comment (antross) [reply packages/extension-browser/src/devtools/utils/storage.ts]: CI passed so I must have been thinking of a different rule 🤷‍♂️

Comment (sarvaje) [reply packages/extension-browser/src/devtools/utils/storage.ts]: Maybe you are thinking on `return`, the linter is configured you require a new line after `const`

**Comment by Hirse** [comment]
@antross Attached the zip and used `Pick`
