### PR TITLE
Fix: Pre-populate known environment data when clicking "Feedback"

### LINKED ISSUE #2711: [Feature] Pre-populate known environment data when clicking "Feedback" link
GitHub issues support providing the value via query string parameters. We can use this to pre-populate data like the version of the extension, enabled categories, etc. so the user doesn't have to. Should make the feedback process less tedious while still giving us good information to help understand issues.

### PR DESCRIPTION
**Pull request by sarvaje**
Fix #2711

## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [ ] Added/Updated related tests.

### CODE REVIEW

File: packages/extension-browser/src/devtools/views/controls/feedback-link.tsx [hunk 1]
```diff
@@ -1,18 +1,86 @@
...
+            body = body.replace(/(<!-- ✍️ Paste the error details here -->)/gim, `$1\n${error.message}\n${error.stack}`);
+        }
+
+        evaluate('window.location', (loc) => {
+            const origin = loc.origin;
+            const noIgnored = ignoredUrls === undefined;
+            const isSameOrigin = !noIgnored && (ignoredUrls === '--webhint-third-party' || ignoredUrls === `^(?!${escapeRegExp(origin)})`);
+            const isCustom = !noIgnored && !isSameOrigin;
+
+            body = body.replace(getRegex('None'), `* [${noIgnored ? 'x' : ' '}] $2`)
```
Comment (antross) [inline packages/extension-browser/src/devtools/views/controls/feedback-link.tsx]:
```suggestion
            body = body.replace('[x] None', `[${noIgnored ? 'x' : ' '}] None`)
```

File: packages/extension-browser/src/devtools/views/controls/feedback-link.tsx [hunk 2]
```diff
@@ -1,18 +1,86 @@
...
+                .replace(getRegex('Different origin'), `* [${isSameOrigin ? 'x' : ' '}] $2`)
```
Comment (antross) [inline packages/extension-browser/src/devtools/views/controls/feedback-link.tsx]:
```suggestion
                .replace('[ ] Different origin', `[${isSameOrigin ? 'x' : ' '}] Different origin`)
```

File: packages/extension-browser/src/devtools/views/controls/feedback-link.tsx [hunk 3]
```diff
@@ -1,18 +1,86 @@
...
+                .replace(getRegex('Custom: <!-- Custom ignored resources -->'), `* [${isCustom ? 'x' : ' '}] Custom: ${isCustom ? ignoredUrls : ''} <!-- Custom ignored resources -->`);
```
Comment (antross) [inline packages/extension-browser/src/devtools/views/controls/feedback-link.tsx]:
```suggestion
                .replace('[ ] Custom: <!-- Custom ignored resources -->'), `[${isCustom ? 'x' : ' '}] Custom: ${isCustom ? ignoredUrls : ''}`);
```

File: packages/extension-browser/src/devtools/views/controls/feedback-link.tsx [hunk 4]
```diff
@@ -1,18 +1,86 @@
...
+            body = body.replace(urlRegex, `__URL for which webhint failed:__ ${loc.href}`);
```
Comment (antross) [inline packages/extension-browser/src/devtools/views/controls/feedback-link.tsx]:
```suggestion
            body = body.replace('__URL for which webhint failed:__', `__URL for which webhint failed:__ ${loc.href}`);
```

File: packages/extension-browser/src/devtools/views/controls/feedback-link.tsx [hunk 5]
```diff
@@ -1,18 +1,86 @@
...
+
+const webhintVersionRegex = /__webhint\sversion:__/g;
+const browserVersionRegex = /__Browser\sversion:__/g;
+const urlRegex = /__URL\sfor\swhich\swebhint\sfailed:__/g;
 
-const openIssueUrl = 'https://github.com/webhintio/hint/issues/new?labels=type%3Abug&amp;template=2-bug-report-browser.md&amp;title=%5BBug%5D+Bug+description';
+const labels = 'type:bug';
+const title = '[Bug] Bug description';
+
+const getRegex = (value: string) => {
```
[the remark this answers is not in the document]
Comment (antross) [reply packages/extension-browser/src/devtools/views/controls/feedback-link.tsx]: On second thought - let's just use simple string replacements and drop this entirely.

File: packages/extension-browser/src/devtools/views/controls/feedback-link.tsx [hunk 6]
```diff
@@ -1,18 +1,86 @@
...
 /**
  * Link to github to give feedback.
  */
-const FeedbackLink = () => {
+const FeedbackLink = ({ config, error, altText }: Props) => {
+    const [issueUrl, setIssueUrlUrl] = useState('');
+
+    const getLocation = () => {
+        const disabledCategories = config.disabledCategories || [];
+        const browserslists = config.browserslist === undefined ? '' : config.browserslist;
```
Comment (antross) [inline packages/extension-browser/src/devtools/views/controls/feedback-link.tsx]: Since we're just mapping to the empty string anyway...
```suggestion
        const browserslists = config.browserslist || '';
```

File: packages/extension-browser/src/devtools/views/controls/feedback-link.tsx [hunk 7]
```diff
@@ -1,18 +1,86 @@
...
+
+    return new RegExp(baseRegexString.replace('{{value}}', value), 'gmi');
+};
 
 /**
  * Link to github to give feedback.
  */
-const FeedbackLink = () => {
+const FeedbackLink = ({ config, error, altText }: Props) => {
+    const [issueUrl, setIssueUrlUrl] = useState('');
```
Comment (antross) [inline packages/extension-browser/src/devtools/views/controls/feedback-link.tsx]:
```suggestion
    const [issueUrl, setIssueUrl] = useState('');
```

File: packages/extension-browser/src/devtools/views/controls/feedback-link.tsx [hunk 8]
```diff
@@ -1,18 +1,86 @@
...
+            body = body.replace(getRegex('None'), `* [${noIgnored ? 'x' : ' '}] $2`)
+                .replace(getRegex('Different origin'), `* [${isSameOrigin ? 'x' : ' '}] $2`)
+                .replace(getRegex('Custom: <!-- Custom ignored resources -->'), `* [${isCustom ? 'x' : ' '}] Custom: ${isCustom ? ignoredUrls : ''} <!-- Custom ignored resources -->`);
+            body = body.replace(urlRegex, `__URL for which webhint failed:__ ${loc.href}`);
+
+            setIssueUrlUrl(`https://github.com/webhintio/hint/issues/new?labels=${encodeURIComponent(labels)}&template=2-bug-report-browser.md&body=${encodeURIComponent(body)}&title=${encodeURIComponent(title)}`);
+        });
+    };
+
+    useEffect(getLocation);
```
Comment (antross) [inline packages/extension-browser/src/devtools/views/controls/feedback-link.tsx]: Since we're only using `getLocation` here no need to define it as a separate function. Just declare it right inside of `useEffect` as an anonymous lambda.

**Comment by antross** [comment]
@sarvaje Looks like the broken link detection script is still biting us on links that actually work. Not sure why unless we're getting throttled somehow. Strange that it seems to be just this PR that's affected, though so I'm a bit hesitant to merge until we understand what's going on.

**Comment by sarvaje** [comment]
this url: `https://www.cloudflare.com/learning/dns/what-is-dns` is returning a 403 error when I try it in Postman. Maybe they have something to determine if the request comes from a browser or not :s

**Comment by antross** [comment]
@sarvaje what files does a PR have to touch to trigger this script? Are we just not running it for other PRs or are they passing?

**Comment by sarvaje** [comment]
@antross I think `.github/ISSUE_TEMPLATE/2-bug-report-browser.md` is the one triggering the `markdown-link-validator`

**Comment by sarvaje** [comment]
Maybe we need to ignore those links, `markdown-link-validator` should allow us to ignore files.

**Comment by antross** [comment]
> Maybe we need to ignore those links, markdown-link-validator should allow us to ignore files.

Sounds good to me. We've verified those links actually work, but fail in the validator, so I think excluding them as a workaround is fine.

**Comment by antross** [comment]
@sarvaje now I'm seeing some failures in `extension-browser`. Have you rebased on `master` recently? I think there was a similar error I fixed there late last week.

**Comment by antross** [comment]
@sarvaje No luck. I'm going to check out your PR and see if I can repro locally.
