### PR TITLE
Fix: Avoid duplicate reports in nested blocks

### LINKED ISSUE #3037: [Bug] "CSS-Prefix-Order" reports twice for prefixes order when error is in nested selectors in SASS
Create a `.scss` file with this content:

```scss
.todoapp {
	background: #fff;

	h1 {
		text-rendering: optimizeLegibility;
		-webkit-text-rendering: optimizeLegibility;
		-moz-text-rendering: optimizeLegibility;		
	}
}
```

You'll get the following on VS Code:

image

Adding an extra nested level will cause a 3rd report for the same issue:

> 'text-rendering' should be listed after '-moz-text-rendering'.
(css-prefix-order)

### PR DESCRIPTION
**Pull request by antross**
Fix #3037

## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [x] Added/Updated related tests.

### CODE REVIEW

File: packages/hint-css-prefix-order/src/hint.ts [hunk 1]
```diff
@@ -67,7 +67,11 @@ const validatePair = (pair: Partial<DeclarationPair>): boolean => {
 const validateRule = (rule: Rule): DeclarationPair[] => {
     const map = new Map<string, Partial<DeclarationPair>>();
 
-    rule.walkDecls((decl) => {
+    rule.each((decl) => {
```
Comment (molant) [inline packages/hint-css-prefix-order/src/hint.ts]: 🤯
