### PR TITLE
Fix: Add code language to all hints which report a code snippet

### LINKED ISSUE #2568: Add code language to all hints which report a code snippet [1]
Needed to help select the correct syntax highlighting behavior in the browser extension.

### PR DESCRIPTION
**Pull request by sarvaje**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [ ] Added/Updated related tests.

## Short description of the change(s)

Fix #2568

### CODE REVIEW

**Comment by antross** [comment]
@sarvaje That was fewer than I expected - maybe we have some hints which should be including code snippets that don't. At-a-glance I see hint-css-prefix-order as a good candidate to add code snippets to. Also a few of our hints referencing HTTP headers don't emit the header+value as a code snippet yet.

Speaking of which, we should include a type for HTTP headers as well. Maybe also strongly type `codeLanguage` as a tuple like `'css' | 'html' | ...` instead of `string` so we defend against typos.

**Comment by sarvaje** [comment]
> Speaking of which, we should include a type for HTTP headers as well. Maybe also strongly type codeLanguage as a tuple like 'css' | 'html' | ... instead of string so we defend against typos.

I was thinking about this, but this would be a Breaking change. If we are ok with that, I can do the change.

> I see hint-css-prefix-order as a good candidate to add code snippets to. Also a few of our hints referencing HTTP headers don't emit the header+value as a code snippet yet.

I'm going to review all the hints and see what I we can do :)

**Comment by antross** [comment]
> > Speaking of which, we should include a type for HTTP headers as well. Maybe also strongly type codeLanguage as a tuple like 'css' | 'html' | ... instead of string so we defend against typos.

> I was thinking about this, but this would be a Breaking change. If we are ok with that, I can do the change.

Hmm... it's a compile-time breaking change, but not a run-time one. I'd be willing to consider that a "Fix" in my book.

**Comment by sarvaje** [comment]
> Hmm... it's a compile-time breaking change, but not a run-time one. I'd be willing to consider that a "Fix" in my book.

hahaha ok!

**Comment by sarvaje** [comment]
@antross this should be ready to review.

File: packages/hint/src/lib/hint-context.ts [hunk 1]
```diff
@@ -19,6 +19,8 @@ import { ProblemLocation, Severity } from '@hint/utils/dist/src/types/problems';
 import { Category } from '@hint/utils/dist/src/types/category';
 import { getHTMLCodeSnippet } from '@hint/utils/dist/src/report/get-html-code-snippet';
 
+export type CodeLanguage = 'css' | 'html' | 'http' | 'javascript';
```
Comment (antross) [inline packages/hint/src/lib/hint-context.ts]: Are these the strings we can pass directly to our syntax highlighter? Or will we need to perform some mapping?

Comment (sarvaje) [reply packages/hint/src/lib/hint-context.ts]: they should be the strings to pass directly to the syntax highlighter

File: packages/hint-strict-transport-security/src/hint.ts [hunk 2]
```diff
@@ -160,7 +160,11 @@ export default class StrictTransportSecurityHint implements IHint {
             if (!isHTTPS(resource) && headerValue) {
                 const message = `'strict-transport-security' header should't be specified in pages served over HTTP.`;
 
-                context.report(resource, message, { element });
+                context.report(resource, message, {
+                    codeLanguage: 'http',
+                    codeSnippet: `${capitalizeHeaderName('strict-transport-security')}: ${headerValue}`,
```
Comment (antross) [inline packages/hint-strict-transport-security/src/hint.ts]: Since we're hard-coding the header name anyway using `capitalizeHeaderName` seems a bit overkill...
```suggestion
                    codeSnippet: `Strict-Transport-Security: ${headerValue}`,
```

File: packages/hint-strict-transport-security/src/hint.ts [hunk 3]
```diff
@@ -9,7 +9,7 @@ import { FetchEnd, HintContext, IHint, NetworkData } from 'hint';
 
 import meta from './meta';
 
-const { isRegularProtocol } = network;
+const { capitalizeHeaderName, isRegularProtocol } = network;
```
Comment (antross) [inline packages/hint-strict-transport-security/src/hint.ts]:
```suggestion
const { isRegularProtocol } = network;
```

File: packages/hint-strict-transport-security/src/hint.ts [hunk 4]
```diff
@@ -248,7 +252,11 @@ export default class StrictTransportSecurityHint implements IHint {
             if (isUnderAgeLimit(maxAge, minMaxAgeValue)) {
                 const message = `'strict-transport-security' header 'max-age' value should be more than ${minMaxAgeValue}`;
 
-                context.report(resource, message, { element });
+                context.report(resource, message, {
+                    codeLanguage: 'http',
+                    codeSnippet: `${capitalizeHeaderName('strict-transport-security')}: ${headerValue}`,
```
Comment (antross) [inline packages/hint-strict-transport-security/src/hint.ts]:
```suggestion
                    codeSnippet: `Strict-Transport-Security: ${headerValue}`,
```

File: packages/hint-validate-set-cookie-header/src/hint.ts [hunk 5]
```diff
@@ -6,10 +6,11 @@ import { debug as d } from '@hint/utils/dist/src/debug';
 import { normalizeString } from '@hint/utils/dist/src/misc/normalize-string';
 import { isHTTPS } from '@hint/utils/dist/src/network/is-https';
 import { isRegularProtocol } from '@hint/utils/dist/src/network/is-regular-protocol';
-import { FetchEnd, IHint, Severity } from 'hint/dist/src/lib/types';
-import { ParsedSetCookieHeader } from './types';
-import { HintContext } from 'hint/dist/src/lib/hint-context';
+import { capitalizeHeaderName } from '@hint/utils/dist/src/network/capitalize-header-name';
```
Comment (antross) [inline packages/hint-validate-set-cookie-header/src/hint.ts]:
```suggestion
```

File: packages/hint-validate-set-cookie-header/src/hint.ts [hunk 6]
```diff
@@ -282,20 +283,30 @@ export default class ValidateSetCookieHeaderHint implements IHint {
...
+                        codeLanguage,
+                        codeSnippet,
+                        element
+                    });
                 });
             };
 
             for (const setCookieHeader of setCookieHeaders) {
                 let parsedSetCookie: ParsedSetCookieHeader;
+                const codeSnippet = `${capitalizeHeaderName('set-cookie')}: ${setCookieHeader}`;
```
Comment (antross) [inline packages/hint-validate-set-cookie-header/src/hint.ts]:
```suggestion
                const codeSnippet = `Set-Cookie: ${setCookieHeader}`;
```

File: packages/hint-x-content-type-options/src/hint.ts [hunk 7]
```diff
@@ -12,6 +12,7 @@
 import { debug as d } from '@hint/utils/dist/src/debug';
 import { normalizeString } from '@hint/utils/dist/src/misc/normalize-string';
 import { isDataURI } from '@hint/utils/dist/src/network/is-data-uri';
+import { capitalizeHeaderName } from '@hint/utils/dist/src/network/capitalize-header-name';
```
Comment (antross) [inline packages/hint-x-content-type-options/src/hint.ts]:
```suggestion
```

File: packages/hint-x-content-type-options/src/hint.ts [hunk 8]
```diff
@@ -46,7 +47,11 @@ export default class XContentTypeOptionsHint implements IHint {
             }
 
             if (headerValue !== 'nosniff') {
-                context.report(resource, `'x-content-type-options' header value should be 'nosniff', not '${headerValue}'.`, { element });
+                context.report(resource, `'x-content-type-options' header value should be 'nosniff', not '${headerValue}'.`, {
+                    codeLanguage: 'http',
+                    codeSnippet: `${capitalizeHeaderName('x-content-type-options')}: ${headerValue}`,
```
Comment (antross) [inline packages/hint-x-content-type-options/src/hint.ts]:
```suggestion
                    codeSnippet: `X-Content-Type-Options: ${headerValue}`,
```

File: packages/hint-highest-available-document-mode/src/hint.ts [hunk 9]
```diff
@@ -13,6 +13,7 @@ import { HttpHeaders } from '@hint/utils/dist/src/types/http-header';
 import { normalizeString } from '@hint/utils/dist/src/misc/normalize-string';
 import { isLocalFile } from '@hint/utils/dist/src/network/is-local-file';
 import { HTMLDocument, HTMLElement } from '@hint/utils/dist/src/dom/html';
+import { capitalizeHeaderName } from '@hint/utils/dist/src/network/capitalize-header-name';
```
Comment (antross) [inline packages/hint-highest-available-document-mode/src/hint.ts]:
```suggestion
```

File: packages/hint-highest-available-document-mode/src/hint.ts [hunk 10]
```diff
@@ -68,20 +69,22 @@ export default class HighestAvailableDocumentModeHint implements IHint {
                 return;
             }
 
+            const codeSnippet = `${capitalizeHeaderName('content-type')}: ${originalHeaderValue}`;
```
Comment (antross) [inline packages/hint-highest-available-document-mode/src/hint.ts]:
```suggestion
            const codeSnippet = `Content-Type: ${originalHeaderValue}`;
```

File: packages/hint-strict-transport-security/src/hint.ts (hunk 2 above)
Comment (sarvaje) [reply packages/hint-strict-transport-security/src/hint.ts]: Completely agree.

**Comment by sarvaje** [comment]
@antross this should be done
