### PR TITLE
Fix: Track `FirstRun` events in CI differently

### LINKED ISSUE #2962: [Bug] Don't log `FirstRun` when `isCI` is true
CI environments aren't typically going to preserve state between runs so if someone allows telemetry, we can end up sending `FirstRun` events on every run.

### PR DESCRIPTION
**Pull request by molant**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- ~~Added/Updated related documentation.~~
- ~~Added/Updated related tests.~~

## Short description of the change(s)

Send `CIRun` events when the user gives permission for telemetry instead
of `FirstRun` so it is easier to know when there are new users and how
many times it is used from CI.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Fix #2962

### CODE REVIEW

**Comment by molant** [comment]
After syncing with @antross we've seen there are some inconsistencies with the `FirstRun` and `SecondRun` events being sent from multiple places.

I'll repurpose this PR to clean up a bit the code and make it more consistent.

**Comment by molant** [comment]
This is ready for another review

File: packages/hint/src/bin/hint.ts [hunk 1]
```diff
@@ -12,33 +12,22 @@
...
 
-const tracking = (/--tracking[=\s]+([^\s]*)/i).exec(process.argv.join(' '));
+const telemetry = (/--tracking[=\s]+([^\s]*)/i).exec(process.argv.join(' '));
 
-import { configStore, appInsights } from '@hint/utils';
+import { appInsights } from '@hint/utils';
 
-const trackingEnv = process.env.HINT_TRACKING;
-let enableTracking;
+const telemetryEnv = process.env.HINT_TRACKING;
```
Comment (sarvaje) [inline packages/hint/src/bin/hint.ts]: Should we change also the env variable?

Comment (molant) [reply packages/hint/src/bin/hint.ts]: There's an issue for that (#2995). I don't want to make a breaking change right now.

Comment (sarvaje) [reply packages/hint/src/bin/hint.ts]: ok!

**Comment by sarvaje** [comment]
You need to update the tests :)

**Comment by molant** [comment]
> You need to update the tests :)

Yes, for whatever reason I had a comment saying that I'll update them once everyone was OK but I don't see it 🤔

File: packages/hint/src/bin/hint.ts [hunk 2]
```diff
@@ -12,33 +12,22 @@
...
+let enableTelementry;
```
Comment (antross) [inline packages/hint/src/bin/hint.ts]:
```suggestion
let enableTelemetry;
```

File: packages/hint/src/lib/cli/analyze.ts [hunk 3]
```diff
@@ -104,46 +104,64 @@ const pruneUserConfig = (userConfig: UserConfig) => {
...
+     * No need to check for CI as state is not persisted and
+     * `alreadyRun` will always be `false`.
+     */
+    if (alreadyRun) {
+        appInsights.trackEvent('SecondRun');
     }
 
-    appInsights.disable();
+    const prunedUserConfig = pruneUserConfig(userConfig);
+    const payload = { ...{ ci: isCI }, ...prunedUserConfig };
```
Comment (antross) [inline packages/hint/src/lib/cli/analyze.ts]: No need to create an intermediate object here.

```suggestion
    const payload = { ci: isCI, ...prunedUserConfig };
```

**Comment by molant** [comment]
I've done some changes. Now we don't have `FirstRun` nor `SecondRun`. I believe we were reporting `SecondRun` for all subsequent runs. I've added a new property that tells if it is been run before.

@hxlnt can you please take a look to make sure you are OK with these changes?

File: packages/hint/src/lib/cli/analyze.ts [hunk 4]
```diff
@@ -104,46 +104,55 @@ const pruneUserConfig = (userConfig: UserConfig) => {
...
+    if (!telemetryEnabled) {
         return;
     }
 
-    appInsights.disable();
+    appInsights.trackEvent('analyze', {
+        ...{
+            ci: isCI,
+            previouslyRun: alreadyRun
+        },
```
Comment (antross) [inline packages/hint/src/lib/cli/analyze.ts]: Similar to my earlier feedback, there's no need to create an intermediate object that we just throw away:

```ts
    appInsights.trackEvent('analyze', {
        ci: isCI,
        previouslyRun: alreadyRun,
        ...pruneUserConfig(userConfig)
    });
```

File: packages/hint/src/lib/cli/analyze.ts [hunk 5]
```diff
@@ -104,46 +104,55 @@ const pruneUserConfig = (userConfig: UserConfig) => {
...
 
+    if (!telemetryEnabled) {
         return;
     }
 
-    appInsights.disable();
+    appInsights.trackEvent('analyze', {
+        ...{
+            ci: isCI,
+            previouslyRun: alreadyRun
```
Comment (antross) [inline packages/hint/src/lib/cli/analyze.ts]: I like having this switched to a property. 

It also got me thinking, for the browser and VS Code extensions we added a `*-telemetry` event (`f12-telemetry` or `vscode-telemetry` respectively) to report when a user opts-in to telemetry for the first time. Think we should do something similar in this PR or leave it as a separate task?

File: packages/hint/src/lib/cli/analyze.ts (hunk 4 above)
Comment (molant) [reply packages/hint/src/lib/cli/analyze.ts]: Done

File: packages/hint/src/lib/cli/analyze.ts (hunk 5 above)
Comment (molant) [reply packages/hint/src/lib/cli/analyze.ts]: I've renamed all the events to `cli-*` and added an opt-in event.

**Comment by molant** [comment]
Ready for another round
