### PR TITLE
Fix: Error location for HTTP headers and added code snippet.

### LINKED ISSUE #2209: [Bug] Bogus error locations for HTTP Headers
Hints like `hint-content-type` which point to HTTP headers also include a location, however this location appears to point to a location in the HTML file that triggered the request (as opposed to the listed resource that contains the HTTP header).

This should be fixed to omit line/column information in these cases as it doesn't make sense.

Actual:
```
'content-type' header charset value should be 'utf-8'
https://www.google-analytics.com/analytics.js:1:17293
```

Expected:
```
'content-type' header charset value should be 'utf-8'
https://www.google-analytics.com/analytics.js
```

### PR DESCRIPTION
**Pull request by sarvaje**
Fix #2209

## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [x] Added/Updated related tests.

### CODE REVIEW

**Comment by sarvaje** [comment]
@molant @antross can you take a look if you like the solution. If so, I will continue working to apply it to other hints.

**Comment by molant** [comment]
I like where this is going :)

File: packages/hint/src/lib/hint-context.ts [hunk 1]
```diff
@@ -138,7 +140,8 @@ export class HintContext<E extends Events = Events> {
             codeSnippet || sourceCode || '',
             position,
             message,
-            resource
+            resource,
+            options.codeLanguage
```
Comment (antross) [inline packages/hint/src/lib/hint-context.ts]: Not sure we need to do it in this PR, but it'd be nice to refactor `engine.report` to take something similar to `ReportOptions` instead of continuing to add extra parameters...

Comment (molant) [reply packages/hint/src/lib/hint-context.ts]: I've opened https://github.com/webhintio/hint/issues/2276

**Comment by sarvaje** [comment]
> One request: let's capitalize header names in the code snippets (e.g. Content-Type: ... instead of content-type: ...) to align with how they're typically displayed in the Network tab of the devtools

Ok! I will do it.

File: packages/hint/src/lib/hint-context.ts (hunk 1 above)
Comment (sarvaje) [reply packages/hint/src/lib/hint-context.ts]: I think this is a breaking change, so it would be nice to have it sooner rather than later.

**Comment by sarvaje** [comment]
@antros @molant ready to review again

File: packages/hint/src/lib/hint-context.ts (hunk 1 above)
Comment (molant) [reply packages/hint/src/lib/hint-context.ts]: I agree, we have quite a few breaking changes already. The blogpost is going to be quite big...

Comment (antross) [reply packages/hint/src/lib/hint-context.ts]: "How we rebuilt webhint from the ground up..." 🤣
