### PR TITLE
Fix: Check detach mode in close method

### LINKED ISSUE #4089: [Feature] Allow connector puppeteer to disable writing to disk
## What scenarios will this solve?

Azure function consumption plan doesn't allow to write on any part of the disk, only in the tmp folder.

We have three options:
1. Modify the path where the connector save the files to the tmp folder.
2. Add a flag to NOT write in disk.
3. Add a flag to write in disk.

The writing is made to avoid lunching multiple browsers during the tests, so maybe options 3 is the better. 

@antross @molant thoughts?

### PR DESCRIPTION
**Pull request by sarvaje**
Fix #4089

## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [ ] Added/Updated related tests.

### CODE REVIEW

File: packages/connector-puppeteer/src/lib/lifecycle.ts [hunk 1]
```diff
@@ -256,7 +256,9 @@ export const close = async (browser: puppeteer.Browser, page: puppeteer.Page) =>
         return;
     }
 
-    await lock();
+    if (options && options.detached) {
```
Comment (molant) [inline packages/connector-puppeteer/src/lib/lifecycle.ts:259]: Wouldn't it be better to just lock when is really needed?
I think the way it is right now we will be delaying closing tabs for all of the even though it is not needed. Or is it for assurance and avoid racing conditions?

Comment (sarvaje) [reply packages/connector-puppeteer/src/lib/lifecycle.ts:259]: I don' t remember exactly why the lock here, but I think it is to avoid racing conditions.

**Review by antross — APPROVED** [review]
