### PR TITLE
Fix: Update 'hint-sri' to work with 'connector-local'

### LINKED ISSUE #1632: Update `hint-sri` to work with `connector-local` and validate external resources [2]
Currently this hint relies on external resources being fetched, but `connector-local` intentionally doesn't fetch external resources as it works with static files.

I propose we update this hint to fetch *external* resources (e.g. from a CDN) itself when running locally. Local files would be difficult to validate as they're potentially changing frequently... perhaps we could do something special for items coming from `package.json` dependencies. This should likely also include some caching to avoid an abundance requests to external resources from repeated runs during development.

### PR DESCRIPTION
**Pull request by sarvaje**
Fix #1632

## Pull request checklist

Make sure you:

- [X] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [X] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [X] Added/Updated related tests.

### CODE REVIEW

**Comment by molant** [comment]
@sarvaje looks like there are some issues with CI. Can you check if they are because of your changes?

**Comment by antross** [comment]
@sarvaje Let's add `hint-sri` to `configuration-development` as part of this change too.

File: packages/hint-sri/src/hint.ts [hunk 1]
```diff
@@ -296,17 +362,126 @@ Actual:   ${hashes.join(', ')}`;
...
+         * for local files.
+         */
+        if (resource.startsWith('file://')) {
+            debug(`Ignoring local resource: ${resource}`);
+
+            return;
+        }
+
+        /*
+         * Requester is not included in webpack bundle for `extension-browser`.
```
Comment (antross) [inline packages/hint-sri/src/hint.ts]:
```suggestion
         * `requestAsync` is not included in webpack bundle for `extension-browser`.
```

Maybe also worth commenting why we're NOT using `Requester` here.

File: packages/hint-sri/tests/fixtures/local-no-pass/test.html [hunk 2]
```diff
@@ -0,0 +1 @@
+<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/core.js" integrity="sha256-YCbKJH6PpUlk130udu/JepdKVpXjdEyzje+z1pE=" crossorigin="anonymous"></script>
```
Comment (antross) [inline packages/hint-sri/tests/fixtures/local-no-pass/test.html]: Nit: include newlines at the end of this and the other test files.

**Comment by sarvaje** [comment]
@antross done!

**Comment by molant** [comment]
@sarvaje can we have #1828 in this PR as well?

File: packages/hint-sri/src/hint.ts [hunk 3]
```diff
@@ -296,17 +362,130 @@ Actual:   ${hashes.join(', ')}`;
...
+        /*
+         * 'this.isScriptOrLink' has already checked
+         * that the src attribute exists, so it is safe to use !.
+         */
+        evt.resource = new URL(evt.element.getAttribute('src')!, evt.resource).href;
+        await this.validateElement(evt, origin);
+    }
+
+    /** Validation entry point for events element::link */
+    private async validateStyleElement(evt: ElementFound) {
```
Comment (molant) [inline packages/hint-sri/src/hint.ts]: Can't this be combined with `validateScriptElement`?
Both seem to do the same thing and the only thing that changes is  the attribute to get (`src` or `href`).

File: packages/hint-sri/src/hint.ts [hunk 4]
```diff
@@ -296,17 +362,130 @@ Actual:   ${hashes.join(', ')}`;
         debug(`Validating integrity of: ${evt.resource}`);
 
         await everySeries(validations, async (validation: Function) => {
-            return await validation(evt);
+            return await validation(evt, origin, cacheErrors);
         });
     }
 
+    private async validateElement(evt: ElementFound, origin: string) {
+        if (this.isInCache(evt)) {
```
Comment (molant) [inline packages/hint-sri/src/hint.ts]: I think we should try to follow the code flow we had earlier with `validateResource` where we have all the checks in `validations` and split `validateElement` into multiple separate checks (and have a single `validate` method).

E.g.:
```ts
private async isScanEnded(evt, origin) {
            /*
             * The item is cached. For the VSCode extension and the
             * local connector with option 'watch' activated we
             * should report what we have in the cache after the
             * first 'scan::end'.
             */
            if (this.scanEnded) {
                const promises = this.getCache(evt).map((error) => {
                    this.context.report(error.resource, error.message, error.options);
                });

                 await Promise.all(promises);

                 return true;  
            }

             return false;
}

private async isLocalResource(evt, origin) {
        const { resource, element } = evt;
        if (resource.startsWith('file://')) {
            debug(`Ignoring local resource: ${resource}`);

             return Promise.resolve(true);
        }
        return Promise.resolve(false);
}

// And add this checks to `validations` and use the same entry point for all the event handlers
... 
```

**Comment by sarvaje** [comment]
> @sarvaje can we have #1828 in this PR as well?

I created a new PR because that is in another hint, but I can move it here if you prefer that.

**Comment by molant** [comment]
Nervermind, I thought it was the same hint.

File: packages/hint-sri/src/hint.ts (hunk 4 above)
Comment (sarvaje) [reply packages/hint-sri/src/hint.ts]: The think is that if we move all of this to the validation flow, how and when do you do the request to get the content of the element?

It would be weird to have a step in the validation that just download something.

File: packages/hint-sri/src/hint.ts [hunk 5]
```diff
@@ -340,139 +340,158 @@ Actual:   ${integrities.join(', ')}`;
...
+            const promises = this.getCache(evt).map((error) => {
+                return this.context.report(error.resource, error.message, error.options);
+            });
 
-                await Promise.all(promises);
-            }
+            await Promise.all(promises);
 
-            return;
+            // Return false to stop the validations.
```
Comment (molant) [inline packages/hint-sri/src/hint.ts]: No need for this comment

File: packages/hint-sri/src/hint.ts [hunk 6]
```diff
@@ -340,139 +340,158 @@ Actual:   ${integrities.join(', ')}`;
...
          *
-         * Note: We are not using `Requester` becuase it depends on `iltorb` and it can
+         * Note: We are not using `Requester` because it depends on `iltorb` and it can
          * cause problems with the vscode-extension because `iltorb` dependens on the
          * node version for which it was compiled.
+         *
+         * We can probably use Requester once https://github.com/webhintio/hint/issues/1604 is done,
+         * and vscode use the node version that support it.
+         *
+         * When the crossorigin="use-credentials" but the response contains
```
Comment (molant) [inline packages/hint-sri/src/hint.ts]: > When using crossorigin="use-credentials" and the response contains
> the header `Access-Control-Allow-Origin` with value `*` Chrome blocks the access

File: packages/hint-sri/src/hint.ts [hunk 7]
```diff
@@ -340,139 +340,158 @@ Actual:   ${integrities.join(', ')}`;
...
+         * the header `Access-Control-Allow-Origin` with value `*` Chrome block the access
+         * to the resource by CORS policy, so we will reach this point
+         * through the traverse of the dom and response.body.content will be ''. In this case,
+         * we have to prevent download any resource.
```
Comment (molant) [inline packages/hint-sri/src/hint.ts]: > we have to prevent the download of the resource.

File: packages/hint-sri/src/hint.ts [hunk 8]
```diff
@@ -340,139 +340,158 @@ Actual:   ${integrities.join(', ')}`;
...
+            return false;
+        }
+
         if (!requestAsync) {
-            return;
+            return true;
+        }
+
+        /*
+         * If the content already exists, we don't need to download it.
```
Comment (molant) [inline packages/hint-sri/src/hint.ts]: Nit: You can collapse and use a single line comment `//` or `/* */` in the same line.

File: packages/hint-sri/src/hint.ts [hunk 9]
```diff
@@ -268,45 +284,227 @@ export default class SRIHint implements IHint {
...
+
+        return Promise.resolve(true);
+    }
+
+    private isNotLocalResource(evt: FetchEnd) {
+        const { resource } = evt;
+
+        /*
+         * If the resource is a local file, ignore the analysis.
+         * The sri usually is added on the building process before publish,
```
Comment (molant) [inline packages/hint-sri/src/hint.ts]: Nit: Move this comment to the beginning of the method:

```js
/**
  * If the resource is...
  */
private isNotLocalResource()
```

**Comment by sarvaje** [comment]
@molant done!

File: packages/hint-sri/src/hint.ts [hunk 10]
```diff
@@ -268,45 +284,224 @@ export default class SRIHint implements IHint {
...
+        }
+
+        return Promise.resolve(true);
+    }
+
+    private async isScanEnded(evt: FetchEnd) {
+        const isInCache = this.isInCache(evt);
+
+        if (this.scanEnded && isInCache) {
+            /*
```
Comment (molant) [inline packages/hint-sri/src/hint.ts]: You forgot to put this comment outside

File: packages/hint-sri/src/hint.ts [hunk 11]
```diff
@@ -268,45 +284,224 @@ export default class SRIHint implements IHint {
...
+            return false;
+        }
+
+        return !isInCache;
+    }
+
+    private async downloadContent(evt: FetchEnd) {
+        const { resource, response, element } = evt;
+
+        /*
```
Comment (molant) [inline packages/hint-sri/src/hint.ts]: And this one too.

**Comment by sarvaje** [comment]
@molant done again hahaha

**Comment by sarvaje** [comment]
@antross done!
