### PR TITLE
Fix: Axe-core throws errors with local iframes

### LINKED ISSUE #5285: [Bug] allowedOrigins value "null" is not a valid origin
# 🐞 Bug report

## Description

When opening a local html with an iframe that has the default CSP webhint throws an error:
`allowedOrigins value "null" is not a valid origin`

image

## Details

- Create a file `test.html` with the following content:
```
<!DOCTYPE html>
<html lang='en'>
<body>
    <div>
        <div>
            <span>iframe: default-src CSP</span>
            <iframe marginwidth="0"
            title="iframe: default-src CSP"
            marginheight="0"
            hspace="0"
            vspace="0"
            frameborder="10"
            scrolling="no" src="http://bing.com"></iframe>
        </div>
    </div>
</body>
</html>
```
- Open webhint and open `test.html`

### PR DESCRIPTION
**Pull request by vidorteg**
## Pull request checklist

Make sure you:

- [x] Signed the Contributor License Agreement (after creating PR)
- [X] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [X] Added/Updated related documentation.
- [X] Added/Updated related tests.

## Short description of the change(s)
Fixes an issue where axe-core throws:
`allowedOrigins value "null" is not a valid origin`

This is due to a axe-core throwing an error instead of finishing the analysis, this is currently an open bug in dequelabs:
`dequelabs/axe-core`
`issue: 3002`

This only manifests under the following conditions:
- local `html` files only
- file has iframes
- the iframes have the `Default` CSP
- The exception gets bubbled and eventually crashes `webhint`. To avoid this the proposed fix is to not scan `iframes` for local `html` files.
-----
Fix #5285

### CODE REVIEW

**Review by flynnolivia — APPROVED** [review]

File: packages/hint-axe/src/util/axe.ts [hunk 1]
```diff
@@ -137,6 +138,20 @@ const withQuotes = (ruleId: string) => {
...
+     * 'allowedOrigins value "null" is not a valid origin'
+     *
+     * This is caused by an axe-core bug which is currently tracked here:
+     * https://github.com/dequelabs/axe-core/issues/3002
+     */
+    let shouldScanIframes = true;
+    const uri = getAsUri(resource);
+
+    if (uri && uri.protocol.includes('file')) {
+        shouldScanIframes = false;
```
Comment (hkal) [inline packages/hint-axe/src/util/axe.ts:152]: nit: The following would allow us to have `shouldScanIframes` as a const:
```
const uri = getAsUri(resource);
const shouldScanIframe = !(uri && uri.protocol.includes('file');
```

**Review by hkal — APPROVED** [review]
Small nit, but otherwise looks good.
