### PR TITLE
Fix: Allow ranged location in css.

### LINKED ISSUE #3130: Dashed CSS property names are only partially underlined in the VS Code extension
E.g. if a report is generated for `background-color`, only `background` ends up underlined.

Fixing this probably requires a few steps:
* Introduce support for ranges on `Problem` (e.g. adding an optional `endColumn` and `endLine`)
* Update affected hints to provide ranges with reports
* Update the VS Code extension to map them to VS Code ranges

### PR DESCRIPTION
**Pull request by sarvaje**
Fix #3130

## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [x] Added/Updated related tests.

## Short description of the change(s)

- [x] Introduce support for ranges on Problem (e.g. adding an optional endColumn and endLine)
- [x] Update affected hints to provide ranges with reports
- [x] Update the VS Code extension to map them to VS Code ranges

### CODE REVIEW

**Comment by sarvaje** [comment]
@molant @antross any idea why this PR is failing? I can't reproduce the error in my machine :(

**Comment by sarvaje** [comment]
Ok, I'm able to reproduce the error.

I think we already discuss this before, but `yarn build` should remove dist before build. Today is the second or third time that I get confuse with the tests because of this change we did long time ago.

**Comment by antross** [comment]
> I think we already discussed this before, but `yarn build` should remove dist before build.

That's what `yarn clean` is for. If we remove `dist` on every build we eliminate files which help rebuilds run faster, notably `tsconfig.tsbuildinfo`.

**Comment by sarvaje** [comment]
Yes, but you need to remember run `yarn clean`...

**Comment by antross** [comment]
@sarvaje Can you add a screenshot of a CSS file in the VS Code extension with these changes? I'm curious to see exactly what gets underlined as part of the new `ChildNode` mapping.

**Comment by sarvaje** [comment]
image

**Comment by molant** [comment]
@sarvaje can you add one with a value underlined?

**Comment by sarvaje** [comment]
do you have an example?

**Comment by sarvaje** [comment]
when a property is not supported I get underlined the property :s

**Comment by sarvaje** [comment]
here is a screenshot.

image

**Comment by antross** [comment]
@sarvaje to ensure you're using your local copy of `hint` and not a shared install you'll need to test this by opening a fixture file that's inside the repo folder. Otherwise the VS Code extension is going to be loading `hint` from `npm` which won't have your changes.

**Comment by sarvaje** [comment]
@molant here is an updated screenshot with all the packages compiled with this version of the code hehehe

image

As you can see, the range includes the property and the value.
I have been talking with @antross and we think we have enough information to take the ranged position of each one (property and value) with some extra work. The only question is if we want to do that or it is ok underlining everything.

**Comment by molant** [comment]
How much extra work would that be? The error is in the value so I think that we should underline only the value but I think I could convince otherwise.

**Comment by antross** [comment]
> The error is in the value

@molant It depends on which error you’re talking about too. The display error would be on the value, but the appearance error would be on the name.

**Comment by molant** [comment]
I meant for the screenshot that @sarvaje shared.

**Comment by sarvaje** [comment]
@molant @antross what do we want to do with this? point only to the property or value, depending on the test, or keep it as is right no?

**Comment by antross** [comment]
If it's not too much work, I think we should point to the property name or value depending on the specific case. 

Go ahead and try to make this work for `hint-css-prefix-order` first. Once that's working I'm happy to pair up to work out plumbing the required data through `hint-compat-api/css`.

**Comment by sarvaje** [comment]
ok!

**Comment by antross** [comment]
And for `display: grid` vs `display: -ms-grid`?

**Comment by sarvaje** [comment]
for now it is only working for properties hehehe

**Comment by sarvaje** [comment]
image

**Comment by antross** [comment]
Looks good - probably worth throwing in a few test cases with weird amounts of white space and content between the name and the value to ensure we've got this right. Some ideas:
```css
.example1 {
    display:     grid;
    display: -ms-grid;
}
.example2 {
    display : grid;
    display : -ms-grid; 
}
.example3 {
    display:
        grid;
    display:
        -ms-grid;
}
.example4 {
    display /* comment */ : /* comment */ grid;
    display: -ms-grid;
}
```

**Comment by sarvaje** [comment]
Those are already covered, now I'm working in a more compliated case:
```
.example4 {
    display /* comment */ :
    /* comment */ grid
    ;
    display: -ms-grid;
}
```

**Comment by sarvaje** [comment]
What about this?

image

**Comment by molant** [comment]
> What about this?

🧐

**Comment by sarvaje** [comment]
Right now is working just for `hint-css-prefix-order` where only the pair property/value can "fail". Should I continue with the other hints?

**Comment by antross** [comment]
Great! Hope it wasn't too crazy to pull off. 😉

**Comment by molant** [comment]
> Should I continue with the other hints?

Yes, please!

File: packages/hint-compat-api/tests/css.ts [hunk 1]
```diff
@@ -86,7 +86,7 @@ testHint(hintPath,
             reports: [
                 {
                     message: `'display: grid' is not supported by Edge < 16. Add 'display: -ms-grid' to support Edge 12+.`,
-                    position: { match: 'display: grid; /* Report */' }
+                    position: { match: 'grid; /* Report */' }
```
Comment (antross) [inline packages/hint-compat-api/tests/css.ts]: I think we should be able to update the `match` logic to allow validating the new ranges as well. 

We can keep the current `string` value for matching the context, then add an optional `range` item to specify the sub-section we want to include. When `range` is present we'll match `endColumn` and `endLine` in addition to `column` and `line`. The necessary updates would be in `findPosition` of `@hint/utils-tests-helpers/src/hint-runner.ts`. 

For example here we could use:
```ts
{ match: 'display: grid; /* Report */', range: 'grid' }
```

What do you think?

Comment (sarvaje) [reply packages/hint-compat-api/tests/css.ts]: Sure, I like the idea

File: packages/utils/src/report/get-css-location-from-node.ts [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+    start.line = end.line;
+    start.column = end.column - node.value.length;
+};
+
+/**
+ * Returns the location of a CSS node.
+ * @param node postcss Node.
+ * @param isValue Indicates if we need the location of the property value.
+ */
+export const getLocationFromNode = (node: ChildNode, isValue?: boolean): ProblemLocation | undefined => {
```
Comment (molant) [inline packages/utils/src/report/get-css-location-from-node.ts]: I think the name should be the same as the file to prevent any confusion and keep things as they are already:
```suggestion
export const getCSSLocationFromNode = (node: ChildNode, isValue?: boolean): ProblemLocation | undefined => {
```

Comment (molant) [inline packages/utils/src/report/get-css-location-from-node.ts]: Also I think we should be consistent with what we have right now in [`json-parser`](https://github.com/webhintio/hint/blob/94dfef55140f6aa9b3dc3d071f9558a4afecb47d/packages/utils/src/json-parser.ts#L28) and accept an `options` object ([`IJSONLocationOptions`](https://github.com/webhintio/hint/blob/94dfef55140f6aa9b3dc3d071f9558a4afecb47d/packages/utils/src/types/json-parser.ts#L3)) in case we need to add more things in the future.

Comment (sarvaje) [reply packages/utils/src/report/get-css-location-from-node.ts]: That type shouldn't be an `interface` :P. I will do it
