### PR TITLE
Fix: Check if browserlist configuration exists before check target hint

### LINKED ISSUE #3388: typescript-config/target error in VS code, but no browserslist.
I am getting "typescript-config/target" error from webhint via VScode extension.
According to the docs, this is checked via looking at browserslist configuration:
https://webhint.io/docs/user-guide/hints/hint-typescript-config/target/
I can't see any browserslist config in my project(Can only browserslist as a dependency in the yarn.lock file.).
What could be causing this issue?

Based on your browser configuration your "compilerOptions.target" should be "ES5". Current one is "ESNext"
(typescript-config/target)webhint

## Environment

* __`hint` version: 1.4.1
* __`Node.js` version: 12.1.0
* __`npm` version: 6.4.1

### PR DESCRIPTION
**Pull request by sarvaje**
Fix #3388

## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [ ] Added/Updated related tests.

### CODE REVIEW

File: packages/hint-typescript-config/src/target.ts [hunk 1]
```diff
@@ -227,10 +229,48 @@ export default class TypeScriptConfigTarget implements IHint {
...
+                packageJsonFolder = null;
+            }
+
+            if (packageJsonFolder) {
+                try {
+                    const packageJson = require(path.join(packageJsonFolder, 'package.json'));
+
+                    return !!packageJson.browserslist;
+                } catch (e) {
+                    console.log(e);
```
Comment (molant) [inline packages/hint-typescript-config/src/target.ts]: Leftover? If not maybe use `debug(e)` and add some more info?

Comment (sarvaje) [reply packages/hint-typescript-config/src/target.ts]: totally leftover.
