### PR TITLE
Fix: Error returned when the config is invalid.

### LINKED ISSUE #1526: "Configuration schema is not valid" - missing feedback why it is invalid
**Propose a new feature/change** 

>   Write a short description of your proposal with (if applicable)
>   some examples of the expected behaviour.

Hi there 👋

I just try out `hint` for the first time. My first use case is running [WCAG2A checks](https://webhint.io/docs/user-guide/hints/hint-axe/#can-the-hint-be-configured). Props for the nice documentation about that 👍

I haven't used `hint` before and so I stripped out the invalid JSON parts and got a configuration like this one:

```json
{
  "hints": {
    "axe": ["error", {
      "runOnly": {
        "type": "tag",
        "values": ["wcag2a"]
      }
    }]
  }
}
```

But running `$ yarn hint http://localhost:9001/` shows this:

```
Configuration schema is not valid
Couldn't find any valid configuration
```

I _guess_ it is, because `connectors` and `formatters` are mandatory? (Because they can be seen [here](https://webhint.io/docs/user-guide/hints/hint-axe/#can-the-hint-be-configured), but without concrete values. However in the [configuration documentation](https://webhint.io/docs/user-guide/configuring-webhint/summary/) it is not highlighted _what_  is actually mandatory.) It would be nice, if the feedback could include the following parts:

1. _What_ was validated? E.g. change "Configuration schema is not valid" to something like "Configuration schema of /path-to/.hintc is not valid", so I know _my_ configuration was actually validated. (I _think_ it was picked up correctly, but I'm not sure.)
2. _Why_ is it invalid? E.g. change "Configuration schema is not valid" to something like "Configuration schema is not valid. The following fields are missing: connectors, formatters." (Similar to the way how Webpack gives feedback to invalid configurations.)

### PR DESCRIPTION
**Pull request by sarvaje**
Fix #1526

Pending tasks:
- [x] Create new object with grouped messages and errors/locations
- [x] Tests location in packages where the schema validation is used.

## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [x] Added/Updated related tests.

### CODE REVIEW

**Comment by alrra** [comment]
`Fix` => `Breaking`

File: packages/hint/src/lib/utils/schema-validator.ts [hunk 1]
```diff
@@ -107,16 +135,94 @@ const generate = (error: ajv.ErrorObject, errors?: ajv.ErrorObject[]): string |
...
+                return error.schemaPath.includes(anyOf.schemaPath) || anyOf.schema.some((schema: any) => {
+                    return error.schemaPath.includes(schema.$ref);
+                });
+            });
+
+            errors = without(groupErrors, ...anyOfErrors);
+
+            allMessages.push(generateAnyOfError(anyOf, anyOfErrors));
+
+
```
Comment (molant) [inline packages/hint/src/lib/utils/schema-validator.ts]: Nit: Remove extra empty line

**Comment by molant** [comment]
@alrra @antross can you please take a 👀 this?

**Comment by molant** [comment]
@sarvaje there are some failing tests, can you please fix them?

**Comment by sarvaje** [comment]
> @sarvaje there are some failing tests, can you please fix them?

sure thing!

**Comment by molant** [comment]
@sarvaje I still see some more failing tests https://travis-ci.org/webhintio/hint/jobs/477610329#L4963

These are in the manifest hint

File: packages/hint-babel-config/src/is-valid.ts [hunk 2]
```diff
@@ -29,15 +29,14 @@ export default class BabelConfigIsValidHint implements IHint {
...
+            const { prettifiedErrors, resource } = fetchEnd;
 
             debug(`parse::error::babel-config::schema received`);
 
-            for (let i = 0; i < errors.length; i++) {
+            for (let i = 0; i < prettifiedErrors.length; i++) {
                 const message = prettifiedErrors[i];
-                const location = errors[i].location;
 
-                await context.report(resource, message, { location });
```
Comment (antross) [inline packages/hint-babel-config/src/is-valid.ts]: Any particular reason `location` was removed? Without it we're not including where the error occurred...

File: packages/hint-typescript-config/src/is-valid.ts [hunk 3]
```diff
@@ -35,15 +35,14 @@ export default class TypeScriptConfigIsValid implements IHint {
...
+            const { prettifiedErrors, resource } = fetchEnd;
 
             debug(`parse::error::typescript-config::schema received`);
 
-            for (let i = 0; i < errors.length; i++) {
+            for (let i = 0; i < prettifiedErrors.length; i++) {
                 const message = prettifiedErrors[i];
-                const location = errors[i].location;
 
-                await context.report(resource, message, { location });
```
Comment (antross) [inline packages/hint-typescript-config/src/is-valid.ts]: Same here. This regresses reporting where a schema error occurred.

File: packages/hint-babel-config/src/is-valid.ts (hunk 2 above)
Comment (sarvaje) [reply packages/hint-babel-config/src/is-valid.ts]: Yes, there is a reason. `errors` is the raw output from `ajv`, and with this PR `prettifiedErrors` can contain more than one `error`. So there is no way to know what location if the one for a `prettifiedError`.

Comment (antross) [reply packages/hint-babel-config/src/is-valid.ts]: We may need a new type of object to return a list of then. Perhaps something to replace `prettifiedErrors` that includes both a `string` and a `location` derived from whichever was the first `error` contained in the entry?

All `error`s contained in a single entry in `prettifiedErrors` should originate from the same location anyway, correct?

**Comment by sarvaje** [comment]
@molant @antross this is ready for another review.

File: packages/hint/tests/lib/utils/schema-validator.ts [hunk 4]
```diff
@@ -48,18 +79,23 @@ test('validate should generate the right message for a type error', (t) => {
     const result: SchemaValidationResult = validate(baseSchema, data);
 
     t.deepEqual(data, result.data);
-    t.is(result.prettifiedErrors[0], `'a' should be string.`);
+    t.is(result.prettifiedErrors[0], `a should be 'string'.`);
```
[the remark this answers is not in the document]
Comment (antross) [reply packages/hint/tests/lib/utils/schema-validator.ts]: Definitely quoted.

Single quotes are fine with me, though backticks may be even better since we're referring to code, but I don't have a strong preference.

File: packages/hint/src/lib/utils/schema-validator.ts [hunk 5]
```diff
@@ -122,6 +208,64 @@ const prettify = (errors: ajv.ErrorObject[]) => {
     return result;
 };
 
+const groupMessages = (errors: ISchemaValidationError[]): GroupedError[] => {
```
Comment (antross) [inline packages/hint/src/lib/utils/schema-validator.ts]: There's a lot going on here. May be worth a comment explaining what the routine does (criteria for grouping, an example, etc.).

File: packages/hint/src/lib/utils/schema-validator.ts [hunk 6]
```diff
@@ -107,13 +154,52 @@ const generate = (error: ajv.ErrorObject, errors?: ajv.ErrorObject[]): string |
     }, error.message || '');
 };
 
+/**
+ * Returns a readable error for 'anyOf' and 'oneOf' errors.
```
Comment (antross) [inline packages/hint/src/lib/utils/schema-validator.ts]: Including examples in the comments would help.

File: packages/hint/tests/lib/utils/schema-validator.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (sarvaje) [reply packages/hint/tests/lib/utils/schema-validator.ts]: done!

**Comment by sarvaje** [comment]
@antross I have added some comments, can you take a look if they look good?

**Comment by antross** [comment]
@sarvaje Looks good. Thanks!
