### PR TITLE
Fix: Ignore resources from other extensions

### LINKED ISSUE #2916: [Extension bug] Ignore resources used by extensions (e.g.: `chrome-extension://`)
Windows 8.1
Chrome 76
Webhint extension 0.0.7

I'm using the suggested .htaccess file by webhint. It contains the content-type for webmanifest:

`AddType application/manifest+json                   webmanifest`

It also has:

`AddDefaultCharset utf-8`

...as well as an explicit `AddCharset utf-8` for several file types, including webmanifest. 

The extension throws this hint:

> hint 1: 'content-type' header value should not contain 'charset=utf-8'.
> https://thomasbrodhead.com/favicons/site.20190903064115.webmanifest
> Content-Type: application/manifest+json; charset=utf-8

Please help.

### PR DESCRIPTION
**Pull request by molant**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- ~~Added/Updated related documentation.~~
- ~~Added/Updated related tests.~~

## Short description of the change(s)

Fix #2916

### CODE REVIEW

File: packages/extension-browser/src/content-script/connector.ts [hunk 1]
```diff
@@ -53,14 +53,15 @@ export default class WebExtensionConnector implements IConnector {
...
+
             try {
                 if (this._fetcher.handle(events)) {
                     return;
                 }
                 if (events.fetchEnd) {
                     await this.notifyFetch(events.fetchEnd);
                 }
-                if (events.fetchStart) {
+                if (events.fetchStart && !this.isExtensionResource(events.fetchStart.resource)) {
```
Comment (antross) [inline packages/extension-browser/src/content-script/connector.ts]: Since we need to do this for both fetchStart and fetchEnd, I think I'd prefer an early exit check here like we did for `this._fetcher.handle` and just pass the `events` object to the helper.

File: packages/extension-browser/src/content-script/connector.ts [hunk 2]
```diff
@@ -53,14 +53,15 @@ export default class WebExtensionConnector implements IConnector {
         });
 
         browser.runtime.onMessage.addListener(async (events: Events) => {
+
```
Comment (antross) [inline packages/extension-browser/src/content-script/connector.ts]: Any reason for the extra newline here?

Comment (molant) [reply packages/extension-browser/src/content-script/connector.ts]: None

File: packages/extension-browser/src/content-script/connector.ts (hunk 1 above)
Comment (molant) [reply packages/extension-browser/src/content-script/connector.ts]: See if you like it better now.
