### PR TITLE
Fix: Allow Node.js style resolution in config #5192

### LINKED ISSUE #5169: typescript-config/is-valid does not recognize Node.js `extends` paths
# 🐞 Bug report

The TSConfig `extends` option [explicitly supports](https://www.typescriptlang.org/tsconfig#extends) Node.js style resolution, meaning it is possible to write:

```json
{
    "extends": "@tsconfig/strictest/tsconfig.json"
}
```

This works perfectly fine as far as the TypeScript compiler is concerned, but webhint 6.2.0 doesn't seem to recognize the path:

```
typescript-config/is-valid: 1 hints
hint #1: ENOENT: no such file or directory, open '/myproject/@tsconfig/strictest/tsconfig.json'
```

Normal filesystem paths, e.g. `node_modules/@tsconfig/strictest/tsconfig.json`, work fine.

### PR DESCRIPTION
**Pull request by vidorteg**
## Pull request checklist

Make sure you:

- [ ] Signed the Contributor License Agreement (after creating PR)
- [ ] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [ ] Added/Updated related tests.

## Short description of the change(s)
Fix behavior in final-config where path resolution was done by
using path.resolve instead of require.resolve. This allows NodeJS
fallback behavior when searching for a module
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Fix #5169

### CODE REVIEW

File: packages/utils-json/src/final-config.ts [hunk 1]
```diff
@@ -31,16 +41,23 @@ export const finalConfig = <T extends ExtendableConfiguration> (config: T, resou
...
+            const castedError = error as IParsingError;
 
-        if (configIncludes.includes(configPath)) {
+            if (castedError && castedError.code === 'MODULE_NOT_FOUND') {
+                return getParsingError('Parent configuration missing', resource, error, 'MODULE_NOT_FOUND');
+            }
 
-            const error = new Error(`Circular reference found in file ${lastPath}`) as IParsingError;
-            const originalPathUri = getAsUri(configIncludes[0]);
+            throw error;
```
Comment (antross) [inline packages/utils-json/src/final-config.ts:53]: Is it intentional that this particular case throws instead of returns?
