### PR TITLE
Fix: Update 'ava' to 'v1.1.0' [1.5]

### LINKED ISSUE #1597: Update tests to use ava 1.0 [1.5]
Filing a task since this affects nearly all of our packages and there are quite a few breaking changes to work through: https://github.com/avajs/ava/releases/tag/v1.0.1

### PR DESCRIPTION
**Pull request by sarvaje**
Fix #1597

## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/hint)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [x] Added/Updated related tests.

### CODE REVIEW

**Comment by molant** [comment]
@sarvaje can you please rebase and fix the conflicts?

**Comment by sarvaje** [comment]
> @sarvaje can you please rebase and fix the conflicts?

Sure thing.

File: packages/create-parser/tests/handlebars-utils.ts [hunk 1]
```diff
@@ -20,5 +20,10 @@ test('compile template uses the `dependencyVersion` helper', async (t) => {
 });
 
 test('compile throws an error if template is not found', async (t) => {
-    await t.throws(handlebars.compileTemplate(path.join(__dirname, 'idontexist.hbs'), {}));
+    t.plan(1);
+    try {
```
Comment (molant) [inline packages/create-parser/tests/handlebars-utils.ts]: Why this change? `t.throws` doesn't work anymore?

File: packages/create-parser/tests/new-parser.ts [hunk 2]
```diff
@@ -1,13 +1,24 @@
...
 
 import * as handlebarsUtils from '../src/handlebars-utils';
 
+type NewParserContext = {
+    sandbox: sinon.SinonSandbox;
+    fsExtraCopyStub: sinon.SinonStub;
+    normalizeStringByDelimiterDefaultStub: sinon.SinonStub;
+    readFileAsyncDefaultStub: sinon.SinonStub;
+    writeFileAsyncDefaultStub: sinon.SinonStub;
+    handlebarsUtilsCompoileTemplateStub: sinon.SinonStub;
```
Comment (molant) [inline packages/create-parser/tests/new-parser.ts]:
```suggestion
    handlebarsUtilsCompileTemplateStub: sinon.SinonStub;
```

File: packages/create-parser/tests/new-parser.ts [hunk 3]
```diff
@@ -35,27 +46,19 @@ proxyquire('../src/new-parser', {
...
-        writeFileAsync
-    };
-    t.context.handlebars = handlebarsUtils;
+    const sandbox = sinon.createSandbox();
+
+    t.context.fsExtraCopyStub = sandbox.stub(fsExtra, 'copy').resolves();
+    t.context.writeFileAsyncDefaultStub = sandbox.stub(writeFileAsync, 'default').resolves();
+    t.context.normalizeStringByDelimiterDefaultStub = sandbox.stub(normalizeStringByDelimiter, 'default').returns('');
+    t.context.readFileAsyncDefaultStub = sandbox.stub(readFileAsync, 'default').resolves('');
+    t.context.handlebarsUtilsCompoileTemplateStub = sandbox.stub(handlebarsUtils, 'compileTemplate').resolves('');
```
Comment (molant) [inline packages/create-parser/tests/new-parser.ts]:
```suggestion
    t.context.handlebarsUtilsCompileTemplateStub = sandbox.stub(handlebarsUtils, 'compileTemplate').resolves('');
```

File: packages/create-parser/tests/new-parser.ts [hunk 4]
```diff
@@ -79,14 +82,12 @@ test.serial('It should create a new official parser.', async (t) => {
     const result = await newParser();
 
     // 6 files (2 code + test + doc + tsconfig.json + package.json)
-    t.is(t.context.handlebars.compileTemplate.callCount, 6, `Handlebars doesn't complile the right number of files`);
+    t.is(t.context.handlebarsUtilsCompoileTemplateStub.callCount, 6, `Handlebars doesn't complile the right number of files`);
```
Comment (molant) [inline packages/create-parser/tests/new-parser.ts]:
```suggestion
    t.is(t.context.handlebarsUtilsCompileTemplateStub.callCount, 6, `Handlebars doesn't complile the right number of files`);
```

File: packages/create-parser/tests/new-parser.ts [hunk 5]
```diff
@@ -121,36 +122,33 @@ test.serial('It should create a new official parser with no duplicate events.',
...
         return question.name === 'event';
     });
-    const eventList = eventQuestion.choices;
-    const containFetchEnd = eventList.includes('fetch::end::*');
-    const containElement = eventList.includes('element::');
-    const data = t.context.handlebars.compileTemplate.args[0][1];
+    const eventList = eventQuestion!.choices as Array<string>;
+    const containFetchEnd = eventList!.includes('fetch::end::*');
+    const containElement = eventList!.includes('element::');
+    const data = t.context.handlebarsUtilsCompoileTemplateStub.args[0][1];
```
Comment (molant) [inline packages/create-parser/tests/new-parser.ts]:
```suggestion
    const data = t.context.handlebarsUtilsCompileTemplateStub.args[0][1];
```

File: packages/create-parser/tests/new-parser.ts [hunk 6]
```diff
@@ -121,36 +122,33 @@ test.serial('It should create a new official parser with no duplicate events.',
...
     const events = data.events.map((event: { event: string }) => {
         return event.event;
     });
     const eventsSet = new Set(events);
 
     // 6 files (2 code + test + doc + tsconfig.json + package.json)
-    t.is(t.context.handlebars.compileTemplate.callCount, 6, `Handlebars doesn't complile the right number of files`);
+    t.is(t.context.handlebarsUtilsCompoileTemplateStub.callCount, 6, `Handlebars doesn't complile the right number of files`);
```
Comment (molant) [inline packages/create-parser/tests/new-parser.ts]:
```suggestion
    t.is(t.context.handlebarsUtilsCompileTemplateStub.callCount, 6, `Handlebars doesn't complile the right number of files`);
```

File: packages/create-parser/tests/new-parser.ts [hunk 7]
```diff
@@ -174,12 +172,10 @@ test.serial('It should create a new non-official parser.', async (t) => {
     const result = await newParser();
 
     // 7 files (2 code + test + doc + tsconfig.json + package.json + .hintrc)
-    t.is(t.context.handlebars.compileTemplate.callCount, 7, `Handlebars doesn't complile the right number of files`);
+    t.is(t.context.handlebarsUtilsCompoileTemplateStub.callCount, 7, `Handlebars doesn't complile the right number of files`);
```
Comment (molant) [inline packages/create-parser/tests/new-parser.ts]:
```suggestion
    t.is(t.context.handlebarsUtilsCompileTemplateStub.callCount, 7, `Handlebars doesn't complile the right number of files`);
```

File: packages/parser-manifest/tests/tests.ts [hunk 8]
```diff
@@ -201,18 +209,18 @@ test(`'${parseEndEventName}' event is emitted when manifest content is valid`, a
...
-    await createParseTest(t, JSON.stringify(manifestContent), parseStartEventName, parseEndEventName, (tt: GenericTestContext<Context<any>>, result: ManifestParsed) => {
+    await createParseTest(t, JSON.stringify(manifestContent), parseStartEventName, parseEndEventName, (tt: ExecutionContext, result: ManifestParsed) => {
         tt.deepEqual(result.parsedContent, manifestContentParsed);
     });
 });
 
 test(`'${parseEndEventName}' event includes location information`, async (t) => {
     const manifestContent =
-`{
+        `{
```
Comment (molant) [inline packages/parser-manifest/tests/tests.ts]:
```suggestion
`{
```

File: packages/parser-manifest/tests/tests.ts [hunk 9]
```diff
@@ -283,7 +291,7 @@ test(`'${parseErrorSchemaEventName}' event includes location information`, async
     };
 
     const manifestContent =
-`{
+        `{
```
Comment (molant) [inline packages/parser-manifest/tests/tests.ts]:
```suggestion
`{
```

File: packages/create-parser/tests/handlebars-utils.ts (hunk 1 above)
Comment (sarvaje) [reply packages/create-parser/tests/handlebars-utils.ts]: I'm fixing this, because this is not the case and it can be fixed using `t.throwsAsync`, but in some other cases, the problem is that the `reject` doesn't return an error, and `ava` now complains about that.

File: packages/connector-jsdom/tests/invalid-url.ts [hunk 10]
```diff
@@ -26,5 +36,11 @@ test(`[${name}] Load an invalid url throws an error`, async (t) => {
 
     t.context.connector = connector;
 
-    await t.throws(connector.collect(new URL('https://localhome')));
+    t.plan(1);
```
Comment (antross) [inline packages/connector-jsdom/tests/invalid-url.ts]: Another place for avoiding `plan` using `t.throwsAsync` per https://github.com/avajs/ava/blob/master/docs/recipes/when-to-use-plan.md#promises-with-a-catch-block

File: packages/create-hint/tests/handlebars-utils.ts [hunk 11]
```diff
@@ -20,5 +20,10 @@ test('compile template uses the `dependencyVersion` helper', async (t) => {
 });
 
 test('compile throws an error if template is not found', async (t) => {
-    await t.throws(handlebars.compileTemplate(path.join(__dirname, 'idontexist.hbs'), {}));
+    t.plan(1);
```
Comment (antross) [inline packages/create-hint/tests/handlebars-utils.ts]: Another place for avoiding `plan` using `t.throwsAsync`.

File: packages/formatter-summary/tests/tests.ts [hunk 12]
```diff
@@ -13,25 +18,23 @@ import SummaryFormatter from '../src/formatter';
...
+    t.context.loggingLogSpy = sinon.spy(logging, 'log');
 });
 
 test.afterEach.always((t) => {
-    t.context.logger.log.restore();
+    t.context.loggingLogSpy.restore();
 });
 
-test(`Summary formatter doesn't print anything if no values`, (t) => {
+test.serial(`Summary formatter doesn't print anything if no values`, (t) => {
```
Comment (antross) [inline packages/formatter-summary/tests/tests.ts]: Was it a bug that this wasn't `serial` before?

File: packages/hint/tests/lib/cli/analyze.ts [hunk 13]
```diff
@@ -195,15 +193,18 @@ test.serial('If config file does not exist, it should use `web-recommended` as d
     sandbox.stub(config.Configuration, 'validateHintsConfig').returns(validateHintsConfigResult);
 
     sandbox.stub(askQuestion, 'default').resolves(false);
-    await t.notThrows(analyze(actions));
+
+    t.plan(2);
```
Comment (antross) [inline packages/hint/tests/lib/cli/analyze.ts]: Do we need `plan` here?
https://github.com/avajs/ava/blob/master/docs/recipes/when-to-use-plan.md#promises-that-are-expected-to-resolve

File: packages/hint/tests/lib/cli/analyze.ts [hunk 14]
```diff
@@ -223,7 +224,9 @@ test.serial('If config file is an invalid JSON, it should ask to use the default
     sandbox.stub(config.Configuration, 'validateHintsConfig').returns(validateHintsConfigResult);
     sandbox.stub(askQuestion, 'default').resolves(true);
 
-    await t.notThrows(analyze(actions));
+    t.plan(3);
```
Comment (antross) [inline packages/hint/tests/lib/cli/analyze.ts]: Do we need `plan` here?

File: packages/hint/tests/lib/utils/resource-loader.ts [hunk 15]
```diff
@@ -94,9 +94,11 @@ test('loadHint calls loadResource with the right parameters', (t) => {
 
     loadResourceStub.throws({});
 
-    t.throws(() => {
+    try {
         resourceLoader.loadHint('fake-hint');
-    });
+    } catch (e) {
```
Comment (antross) [inline packages/hint/tests/lib/utils/resource-loader.ts]: Is this one of the cases where we can't use `throws` because `e` is not an `Error`?

File: packages/parser-css/tests/basic-tests.ts [hunk 16]
```diff
@@ -17,37 +20,35 @@ const element = {
...
 
-test.serial('We should provide a correct AST when parsing CSS.', async (t) => {
-    const sandbox = sinon.createSandbox();
     const parseObject = {};
     const code = '.foo { color: #fff }';
     const style = `<style>  ${code}  </style>`;
-    new CSSParser.default(t.context.engine); // eslint-disable-line
+    new CSSParser.default(engine); // eslint-disable-line
+
+    const engineEmitASync = sandbox.spy(engine, 'emitAsync');
```
Comment (antross) [inline packages/parser-css/tests/basic-tests.ts]: Minor typo (also will need to update usages).
```suggestion
    const engineEmitAsync = sandbox.spy(engine, 'emitAsync');
```

File: packages/connector-jsdom/tests/invalid-url.ts (hunk 10 above)
Comment (sarvaje) [reply packages/connector-jsdom/tests/invalid-url.ts]: connector.collect doesn't throw an error:
`Promise rejected with exception that is not an error:`

File: packages/formatter-summary/tests/tests.ts (hunk 12 above)
Comment (sarvaje) [reply packages/formatter-summary/tests/tests.ts]: for some reason, it was working before without the serial, but now, with all the changes, it is failing without `.serial`

File: packages/hint/tests/lib/cli/analyze.ts (hunk 13 above)
Comment (sarvaje) [reply packages/hint/tests/lib/cli/analyze.ts]: nope, we don't need it here.

File: packages/hint/tests/lib/utils/resource-loader.ts (hunk 15 above)
Comment (sarvaje) [reply packages/hint/tests/lib/utils/resource-loader.ts]: Yes, but I think it is because the tests are wrong, it should throw an `Error`

**Comment by sarvaje** [comment]
@molant @antross I think all the feedback is fixed

File: packages/connector-jsdom/tests/invalid-url.ts (hunk 10 above)
Comment (antross) [reply packages/connector-jsdom/tests/invalid-url.ts]: Got it.

File: packages/formatter-summary/tests/tests.ts (hunk 12 above)
Comment (antross) [reply packages/formatter-summary/tests/tests.ts]: Honestly it doesn't look like it should have worked reliably before. We may have been on the lucky side of a race condition (or other unexpected ava behavior that kept it from being a race condition). Makes sense to be `serial` now.

Comment (sarvaje) [reply packages/formatter-summary/tests/tests.ts]: Yes, because we are stubbing properties in an object share for both tests.
